### ISSUE TITLE
mdb-schema --opions not working

### ISSUE THREAD

**Issue by usersnehal251190** [mdbtools/mdbtools#110]
I am using --no-drop-table option for mdb-schema but it's not working 
output comes like this :
[root@localhost files]#  mdb-schema --no-drop-table AgeRange.mdb mysql
mdb-schema: invalid option -- '-'
mdb-schema: invalid option -- 'n'
mdb-schema: invalid option -- 'o'
mdb-schema: invalid option -- '-'
mdb-schema: invalid option -- 'd'
mdb-schema: invalid option -- 'r'
mdb-schema: invalid option -- 'o'
mdb-schema: invalid option -- 'p'
mdb-schema: invalid option -- '-'
mdb-schema: invalid option -- 't'
mdb-schema: invalid option -- 'a'
mdb-schema: invalid option -- 'b'
mdb-schema: invalid option -- 'l'
mdb-schema: invalid option -- 'e'

**Comment by evanmiller** [comment]
What version of MDB Tools are you using?

**Comment by evanmiller** [comment]
Since this is an old issue and has not been reported elsewhere I am closing it.
