### ISSUE TITLE
mdb-schema duplicating columns field size

### ISSUE THREAD

**Issue by damnlie** [mdbtools/mdbtools#112]
Hi,

I playing around with mdbtools to replace bullzip on a Linux environment. When I do "mdb-shema test.mdb > test.sql the size of the columns field become double. Do you know maybe why is that and how we can I fix it? Or it's a known bug?

Thanks,
MelindaK

**Comment by evanmiller** [comment]
I'm guessing this is an issue with UTF-16 fields (which use twice as much storage as Latin-1 / ASCII).

**Comment by evanmiller** [comment]
Fixed in 0.9.2
