### ISSUE TITLE
Safety wrt user supplied data

### ISSUE THREAD

**Issue by atdotde** [mdbtools/mdbtools#117]
Hi,

as part of the [Subsurface dive log project](http://subsurface-divelog.org) I would like to write a file format converter web service which uses mdbtools for parsing files that happen to contain access databases. How confident are you that I can run mdbtools on user supplied data on my server? Or do I need to be afraid that a user uploading a specifically crafted file could crash the parser and possibly compromise my server? Of course, one can never be sure but did you have in mind this case of an evil user providing the file to parse when writing the code?

Thanks a lot
Robert

**Comment by evanmiller** [comment]
I have found a large number of buffer overruns in this code base. I would not trust it in its current state to accept user-supplied (or "evil person-supplied") files. I'm working on addressing these issues in my own code branch but it may be a while until the code is battle-tested.
