### ISSUE TITLE
problem with -D option

### ISSUE THREAD

**Issue by ilativ** [mdbtools/mdbtools#12]
Hello,

i try to export Data from tables that have date und datetime fields but the format in both fields is wrong in the export file.
So I that “-D %F” option to get the right format for date fields but I see that that mdb-export apply this format to date and datetime fields. When I that “-D %T” option  I get the right datetime format,  datetime fields have the right format but the date fields format is broken.

Is it possible to that different formats for date and datetime fields on export?

Best regards,
Ilativ

**Comment by evanmiller** [comment]
#162 now includes support for separate -D (date only) and -T (date/time) fields. Closing issue.
