### ISSUE TITLE
mdb-export can not read uncorrectly closed .mdb files

### ISSUE THREAD

**Issue by DaPutzy** [mdbtools/mdbtools#120]
Every 1-2 months one of our server produces a "broken" .mdb file. I do not know the reason for this but I assume its a power outage or someone is pulling the plug, etc.

mdb-export produces the following output:

```
$ mdb-export broken.mdb "DATA_COUNTER"
ID,TIME_START,TIME_END,DEVICE,IN,OUT,DEVICE_SUB1,DST
```

If I open the file with MS Access however, all the data ist there. All I need to do is save the file with MS Access again and mdb-export can read it:

```
$ mdb-export fixed.mdb "DATA_COUNTER"
ID,TIME_START,TIME_END,DEVICE,IN,OUT,DEVICE_SUB1,DST
1,"09/08/17 23:51:17","09/09/17 00:06:17",1,0,0,0,0
2,"09/08/17 23:51:17","09/09/17 00:06:17",2,0,0,0,0
3,"09/08/17 23:51:17","09/09/17 00:06:17",21,0,0,0,0
4,"09/08/17 23:51:17","09/09/17 00:06:17",22,0,0,0,0
5,"09/09/17 00:06:17","09/09/17 00:21:17",1,0,0,0,0
6,"09/09/17 00:06:17","09/09/17 00:21:17",2,0,0,0,0
7,"09/09/17 00:06:17","09/09/17 00:21:17",21,0,0,0,0
8,"09/09/17 00:06:17","09/09/17 00:21:17",22,0,0,0,0
9,"09/09/17 00:21:17","09/09/17 00:36:17",1,0,0,0,0
... etc.
```

I attached both files: [test_files.zip](https://github.com/brianb/mdbtools/files/1306143/test_files.zip)

I have no real unterstanding of the problem, I can only assume mdb-export expects the file to be closed properly,... MS Access seems to be ignoring this.

**Comment by evanmiller** [comment]
Thanks for the report. The "broken.mdb" export is still empty as of the 0.9 release so I am leaving this issue open. See also #139 and #113 for similar reports which may or may not be related.

**Comment by evanmiller** [comment]
Researching this some more, it looks like the "broken" file has a reported row count (`table->num_rows`) of zero. I am guessing this number is merely advisory, and may be set to zero while the file is being edited.

MDB Tools will skip reading a table altogether if the reported row count is zero. I am able to read the "broken" file if I remove the zero-row checks in a couple of places.

For my own notes, here are the patches where the zero-row checks were introduced:

https://github.com/mdbtools/mdbtools/commit/12bd73f38eca21b725cc07e85d605b5a18b2010f

https://github.com/mdbtools/mdbtools/commit/5d2586cde52096877bcb8e182e9aefed306c5cfd

I may be able to remove them both but will need to do some testing.

**Comment by evanmiller** [comment]
The provided file can be read by MDB Tools 0.9.1. If you continue to experience problems reading a file, please open a new issue.

**Comment by LowLevelMahn** [comment]
longtime mdbtools user here - hope to upgrade soon :)

i would not silently remove the row == 0 check, its fully unclear while reading through the code that this is absolutely not a normal/typical situation => empty (or due to error) partial written tables becomes magically the same in the flow - that is ok for the result but not for the documentary character of the code itself

at least you should re-add the check but use a #if defined(DO_ROW_COUNT_CHECK) with an description at definition place
to make it 100% clear that this it not the standard for filled tables and that the ignoring is a way to also read "incorrect" tables

**Comment by evanmiller** [comment]
@LowLevelMahn Thanks for the perspective. Well, one of the problems with the check was that the row_count was only checked for zero. It was not checked against the observed number of rows in the file. So the row_count could be incorrect in a lot of ways and the table would still be read.

If there's a demonstrable case where the change causes MDB Tools to diverge from MS Access then we can revisit the issue.

**Comment by LowLevelMahn** [comment]
> Well, one of the problems with the check was that the row_count was only checked for zero. It was not checked against the observed number of rows in the file. So the row_count could be incorrect in a lot of ways and the table would still be read.

why not add that and check if the actual read row count is equal to the given row count and disable that check (for now) with a #define DISABLE_ROW_COUNT_CHECK - is it normal that these numbers differ that often?

```
row_count from mdb
read table...
if(row_count != read_rows)
{
  error_log("given and read table row count differs - mdb corrupt?");
#if defined(DISABLE_ROW_COUNT_CHECK)
  return errorXYZ;
#else  
}
```

disabling checks is something different then weakening the code in finding unusal stuff

how to differ between corrupts mdbs and perfect mdbs in unit-tests if there is no code at all?

**Comment by evanmiller** [comment]
The purpose of the library is to read from legacy MDB files. I don't think anyone is coming to the library hoping *not* to read from a corrupt file. But the real test should be whether MDB Tools matches Access. The OP on this report indicated that Access was successfully recovering these files.

Additional file integrity checks would be welcome - see for instance #113. There will need to be a discussion about a proper interface. Compile-time flags aren't a great fit for how the project is usually used (pre-compiled).

**Comment by LowLevelMahn** [comment]
> The purpose of the library is to read from legacy MDB files.

until https://github.com/mdbtools/mdbtools/issues/121 is solved :)

> Compile-time flags aren't a great fit for how the
> project is usually used (pre-compiled).

thats true, the question is: what corruptions are currently known/possible and should be allowed?
is mdbtools good in detecting abnormal mdbs?

**Comment by DaPutzy** [comment]
Hey, thanks for looking into this.

> The OP on this report indicated that Access was successfully recovering these files.

Indeed the fix to feeding these files into mdb-export was opening and saving them in Access.
