### ISSUE TITLE
mdb-queries source code. Compiles but does not return results.

### ISSUE THREAD

**Issue by seth-noaa** [mdbtools/mdbtools#122]
Hi all,

Thank you for all the work on mdb-tools. It's great.

I found this code floating around on the sourceforge version message board. It hasn't been updated in a long time, and the bits of patching I did allowed it to compile, and run, but it just gives "abort trap: 6" which I'm unable to track down.

To be clear, I am not the original author of this code. The original author is shown as Lenny Leblanc. The code was attached to a message here from 2005:

https://sourceforge.net/p/mdbtools/mailman/message/5997379/ 

I discerned that the mdb_bind_column function was, at some point, re-worked to take four parameters, while this code passes only 3. Adding a fourth integer to the call let the compiler (on osx) finish. 

If anyone is able to bring this up to date to work with the current release of mdb-tools that would be great.

Cheers, 
Seth

[mdb-queries.c.zip](https://github.com/brianb/mdbtools/files/1350024/mdb-queries.c.zip)

**Comment by evanmiller** [comment]
Hi, thanks for the message. I hadn't seen that tool but I have attempted to adapt it to the modern era. I realize you've likely moved on with your life, but if you have any interest in the tool still, please see the referenced commits above.

**Comment by evanmiller** [comment]
This tool is now included in #162 - please open a new issue if you experience issues with that version. Thanks!

**Comment by seth-noaa** [comment]
@evanmiller : I still deal with many of the same tools now as then. The inclusion of this is a boon. Thank you for all your work! This is awesome!!!
