### ISSUE TITLE
mdb-export crashes while exporting field of type NUMERIC

### ISSUE THREAD

**Issue by myasarfr** [mdbtools/mdbtools#124]
mdb-export crashes while exporting field of type MDB_NUMERIC.

libmdb is crashing in mdb_xfer_bound_data() after calling function mdb_numeric_to_string().
It seems the function mdb_numeric_to_string() is corrupting some memory.

The problem seems to be in function multiply_byte() the following code doesn't seem correct : 
`       for (i=0;i<MAX_NUMERIC_PRECISION;i++) {`
`		if (multiplier[i] == 0) continue;`
`		for (j=0;j<3;j++) {`
`			if (number[j] == 0) continue;`
`			product[i+j] += multiplier[i]*number[j];`
`	...`

In the following line we may write outside the buffer length : 
`	product[i + j] += ...`
when i = (MAX_NUMERIC_PRECISION - 1) and j > 0
because the parameter 'product' is declared as :
`       unsigned char product[MAX_NUMERIC_PRECISION];`

Note : I'm crashing in mdb_numeric_to_string() with the parameters : 
`  prec=19 scale=4`
`  bytes = { 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x64 0xe2 0x4 0x0 }`

**Comment by evanmiller** [comment]
Thanks for the report. It appears that `mdb_numeric_to_string` was copied from `mdb_money_to_string` without updating the data lengths. (Money is 8 bytes, Numeric is 16 bytes). I'll try to come up with a fix soon.

**Comment by evanmiller** [comment]
Fix included in #162, closing
