### ISSUE TITLE
missing txt2man dependancies in doc

### ISSUE THREAD

**Issue by pierreblavy2** [mdbtools/mdbtools#126]
In order to build the project with a manual we need txt2man. 
- This package should be listed in the README file as project dependencies (line 53)
- OR : the README should contains information about how to build without manual (line 96)

The documentation should include a way to configure the installation to a local folder, as you're not always root on the machine, so you may not be able to write to /usr/

Best regards (and good job, this code is very useful)

**Comment by evanmiller** [comment]
Thanks for the report, fix included in #162
