### ISSUE TITLE
postgres insert column doesn't exist

### ISSUE THREAD

**Issue by shorabhd** [mdbtools/mdbtools#128]
I am converting a accdb file to sql file using mdbtools export tables. For insert queries it is generating something like this:

INSERT INTO TABLE_NAME ("COLUMN1", "COLUMN2") VALUES ("ABC", "DEF");

I am getting column doesn't exist on "ABC" since it is in double quotes instead of single quotes.

**Comment by akaspick** [comment]
Use `mdb-export -q "'" -X "'" -I postgres db.mdb`

**Comment by evanmiller** [comment]
This is a duplicate of #119
