### ISSUE TITLE
Reading large text or memory/hyperlinks through odbc

### ISSUE THREAD

**Issue by jimrees** [mdbtools/mdbtools#130]
```
// C++ unixodbc client code:
SObject odbc_string_extractor(SQLHDBC, SQLHSTMT stmt, SQLUSMALLINT icol) {
    char buf[6];     // Using small size here to demonstrate
    memset(buf, 0, sizeof(buf));
    SQLRETURN ret;
    SQLLEN BinaryLenOrInd;
    std::string accum;
    while((ret = SQLGetData(stmt, icol, SQL_CHAR, buf, sizeof(buf)-1, &BinaryLenOrInd))
          != SQL_NO_DATA) {
        SQLINTEGER numBytes = (BinaryLenOrInd > (SQLLEN)(sizeof(buf)-1)
                               ||
                               (BinaryLenOrInd == SQL_NO_TOTAL) ? (sizeof(buf)-1) : BinaryLenOrInd);
        if (true) {
            std::wclog << "ret = " << ret
                       << ", BinaryLenOrInd = " << BinaryLenOrInd
                       << ", numBytes = " << numBytes
                       << ", and buffer = '" << buf << "'"
                       << std::endl;
        }
        accum += std::string(buf, buf+numBytes);
    }
    return make_string(accum.c_str());
}
```
and when a cell contains "4th Dubai International Parachuting Championship 2013", I get:

ret = 1, BinaryLenOrInd = 5, numBytes = 5, and buffer = '4th D'
ret = 1, BinaryLenOrInd = 5, numBytes = 5, and buffer = '4th D'
ret = 1, BinaryLenOrInd = 5, numBytes = 5, and buffer = '4th D'
ret = 1, BinaryLenOrInd = 5, numBytes = 5, and buffer = '4th D'
ret = 1, BinaryLenOrInd = 5, numBytes = 5, and buffer = '4th D'
ret = 1, BinaryLenOrInd = 5, numBytes = 5, and buffer = '4th D'
ret = 1, BinaryLenOrInd = 5, numBytes = 5, and buffer = '4th D'
ret = 1, BinaryLenOrInd = 5, numBytes = 5, and buffer = '4th D'
ret = 1, BinaryLenOrInd = 5, numBytes = 5, and buffer = '4th D'
ret = 1, BinaryLenOrInd = 5, numBytes = 5, and buffer = '4th D'
ret = 0, BinaryLenOrInd = 4, numBytes = 4, and buffer = '013'

and a final output string of "4th D4th D4th D4th D4th D4th D4th D4th D4th D4th D013"

Bug was found in src/odbc.c - creating pull request shortly....

**Comment by evanmiller** [comment]
Fix included in #162
