### ISSUE TITLE
mdb-schema sqlite backend  Constraint not supported by sqlite 

### ISSUE THREAD

**Issue by marcobra** [mdbtools/mdbtools#134]
mdb-schema  mydb.mdb sqlite

...
-- CREATE Relationships ...
ALTER TABLE `PRATICHE_AMMPUB` ADD CONSTRAINT ... 
...

Since contraint isn't supported by sqlite 

https://stackoverflow.com/questions/1884818/how-do-i-add-a-foreign-key-to-an-existing-sqlite-table

can mdb-schema solve this issue by adding some better instruction at table creation code ?

Thank you

**Comment by evanmiller** [comment]
Duplicate of #82
