### ISSUE TITLE
txt2man not found on homebrew server

### ISSUE THREAD

**Issue by ultimatemegs** [mdbtools/mdbtools#135]
Error: No available formula with the name "txt2man" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
Megans-MacBook-Pro:~ meganbarnes$

**Comment by duhaime** [comment]
@ultimatemegs Are you having trouble running mdbtables on OSX? If so, I was able to get this going by using the following steps (outlined [here](https://gist.github.com/duhaime/eaeea5eb2b8d6548fdbe1ff2635f17c4)):

```bash
git clone https://github.com/brianb/mdbtools
cd mdbtools
brew install automake
brew install glib
autoreconf -i -f
./configure --disable-man
make
make install
```

Then, once that all finished, I exported each table from an MDB file like so:

```
import subprocess, shlex

# specify the mdb file (Access DB file) to parse into tsv format
access_db = 'London_Book_Trade_NEW.mdb'

# list the tables available in the db
tables = subprocess.check_output( shlex.split('mdb-tables ' + access_db + ' -1') )
for t in tables.decode('utf-8').split('\n'):
  t = t.strip()
  try:
    print(' exporting table', t)
    # skip empty table names if present
    if not t:
      continue

    content = subprocess.check_output( shlex.split('mdb-export ' + access_db + ' "' + t + '"' ) )
    with open(t + '.tsv', 'w') as out:
      out.write(content.decode('latin1'))
  except Exception as exc:
    print(' could not export table', t, exc)
```

**Comment by pleasemarkdarkly** [comment]
Do the following.

git clone https://github.com/mvertes/txt2man
cd txt2man
make install
txt2man -h
