### ISSUE TITLE
Handling images from Access DB files

### ISSUE THREAD

**Issue by duhaime** [mdbtools/mdbtools#136]
I'm trying to parse a database that contains many images in one table. The images are evidently dumped into a column in the table. When exporting the database with mdbtools, however, those images become malformed in the output file, and introduce lots of breaking whitespace that corrupts the export tsv format. Full steps I'm using are [here](https://gist.github.com/duhaime/eaeea5eb2b8d6548fdbe1ff2635f17c4).

Does anyone know how to export images from an Access db using mdbtools? Any suggestions would be helpful!

**Comment by hijackwust** [comment]
I find export images from an Access db  using "MS Access to MySQL" from http://www.bullzip.com, it is good, but it is used in windows

**Comment by evanmiller** [comment]
Try using `mdb-export` with `--bin=octal`.
