### ISSUE TITLE
There should be a mdb_get_version() function

### ISSUE THREAD

**Issue by n1tehawk** [mdbtools/mdbtools#138]
If programs wish to link against *libmdb* dynamically they have a bit of trouble trying to find out (or verify) the mdbtools version. There's *mdbver.h*, but that only gives you the "interface" version (compile-time, 'client' side) - not the one that's actually in use / correlates to the library that got loaded (at run time).

It would be convenient if the API provided some sort of `const char *mdb_get_version(void)` that returns the `MDB_FULL_VERSION` string of the library itself.

Regards, NiteHawk

**Comment by evanmiller** [comment]
Hi, thank you for the suggestion. The function will be included among the upcoming changes in #162. Closing issue.
