### ISSUE TITLE
mdb-export empty

### ISSUE THREAD

**Issue by ChristianGeng** [mdbtools/mdbtools#139]
When I try to run mdb-export, then I get the data correctly for most of the tables.
But for some, I only get the header. 
However, the table is there, when I open it with MS Access, I can see the data.
In the table I looked at more carefully, the only problem I could detect was that
there was no entry in the last column of the last row - it was empty.
Would that be the explanation, and, if yes, is there a possibility to even epxort
the data if there are incomplete cases?

**Comment by foi** [comment]
I was observe the same when a table have 1 line of data

**Comment by evanmiller** [comment]
Hi, please try the latest 0.9 beta and see if that fixes things: https://github.com/mdbtools/mdbtools/releases

**Comment by evanmiller** [comment]
Hi, since I received a "thumbs up" from @foi and there has been no reply from OP I am closing this issue. If you continue to see the empty output with the 0.9.0 release, please open a new issue with:

* The version of MDB Tools
* The command that you ran
* A link to the
