### ISSUE TITLE
update sourceforge page

### ISSUE THREAD

**Issue by maxogden** [mdbtools/mdbtools#14]
http://mdbtools.sourceforge.net/ comes up in google searches but doesnt mention that mdbtools is still actively maintained here. dunno if this is in your power or not but it would be nice to update that page

**Comment by marnunez** [comment]
Same here. Got here by chance, googling an error.

**Comment by jdkloe** [comment]
The logical thing to do I think would be if one of the original maintainers of the sourceforge project request the project to be removed from sf (Brian?). I have been in the same situation, for another project, and in the end a simple email to sourceforge did the trick. Unfortunately there is no option at all to do this from the user interface for a sf project, so it took me some time to find out that this was needed.

**Comment by jonasstein** [comment]
We want to distribute this software in our Linux distribution. It is important to know, if this is the "real" mdbtools, or a fork. Please clarify here and on the SF page as suggested 6 years ago.

**Comment by evanmiller** [comment]
Hello everyone, this is the "real" mdbtools. We are in the process of updating the Sourceforge to link here. Thank you for your patience.
