### ISSUE TITLE
No tables in Test.mdb

### ISSUE THREAD

**Issue by StepHhan** [mdbtools/mdbtools#143]
Hello,

we installed mdbtools on AIX (compiled by perzl). For testing the tool, I created an Access Database with two tables (table1 and table2). Then, I copied the mdb file (JET4, Access 2000) on the AIX server with WinSCP. Executing the command "mdb-tables Test.mdb" results in an empty line with no table found. 

Has anyone an idea what the problem could be? 

Installation details of mdbtools:

**RPM:**
mdbtools-0.6.cvs20051109-1.aix5.1.ppc.rpm
mdbtools-devel-0.6.cvs20051109-1.aix5.1.ppc.rpm
mdbtools-libs-0.6.cvs20051109-1.aix5.1.ppc.rpm

**Source RPM:**
mdbtools-0.6.cvs20051109-1.src.rpm

**Package dependencies:**
glib2 >= 2.8.1-3
mdbtools-libs = 0.6.cvs20051109-1 (download from above)
readline >= 5.2-3

Thanks a lot

**Comment by evanmiller** [comment]
Hi, if you can provide a test file I will take a look and try to figure out what's going on.

**Comment by evanmiller** [comment]
I see you are using the 0.6 release. If the issue persists with the latest code, then please open a new issue.
