### ISSUE TITLE
Password should check for version (jet 3)

### ISSUE THREAD

**Issue by ying-w** [mdbtools/mdbtools#144]
Recently I was poking around the header of some old mdb files and I wanted to have a better understanding of how it was organized. Looking through file.c, it seems like the masking part (`j ^= key[pos]`) should first check to make sure that it is a Jet 3 db. The mask for Jet 4 db can be found in the code linked [here](http://planetsourcecode.com/vb/scripts/ShowCode.asp?txtCodeId=73390&lngWId=1) inside `frmMain.frm`. 

Out of curiosity, I was wondering if anyone knew how the masks (the `key` array and the values XOR to `mdb->f->db_key`) were generated. The HACKING document states that its a simple RC4 key and [this page](http://jabakobob.net/mdb/first-page.html) gives a key, however, the masks in the code are not part of the keystream generated from that key. Are the masks brute forced?

**Comment by evanmiller** [comment]
@ying-w The first link you gave isn't working - do you have another reference?

**Comment by ying-w** [comment]
@evanmiller thanks for taking over the project. you can close this issue as I am no longer working with mdb files and the source code no longer exists in my downloads folder.

For completeness, I was following [this wiki](http://fileformats.archiveteam.org/wiki/Access) but seems like the website hosting [the code](http://archive.vn/0xEmq) died [earlier this month](https://www.vbforums.com/showthread.php?888045-Re-PlanetSourceCode). The files do exist in [disk 7](https://archive.org/details/PSC-JUMBO_RESOURCE_CD) of the archive, however, my VM of windows 7 isn't able to unzip the file after install. There seems to be some activity on that forum to mirror the code to github, if that happens i'll make another post here.

**Comment by evanmiller** [comment]
Okay, thanks for the additional information. I'll close the issue since there's not much I can do right now. Stay tuned!

**Comment by nirgal** [comment]
The key is [hardcorded](https://github.com/mdbtools/mdbtools/blob/master/src/libmdb/file.c#L245) (0x4ebc8afb)
This doesn't work in all versions.
In some MDB versions, the value should be 0xe15e01b9 (value from comment in the code linked above).
I believe the real way to decode that is to read the mdw file associated with the file. Our values are taken from the mdw files distributed by Microsoft, I believe. I think I remember there was a way to better encrypt the mdb files with a locally generated mdw file...
