### ISSUE TITLE
internal error SHLIBEXT

### ISSUE THREAD

**Issue by andrasgalli** [mdbtools/mdbtools#150]
Hi!

I've installed the mdbtools with the --with-unixodbc argument to OSX Mojave.
I've receiving the following error when trying to use the driver from php 7.2:

internal error, unexpected SHLIBEXT value ('`test .$module = .yes && echo .so || echo .dylib`') may indicate a problem with configure

```php
$connStr = 'odbc:DRIVER={MDBTools};DBQ="' . $mdbFilePath . '";';
$dbh = new \PDO($connStr);
$dbh->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
```

**Comment by steezer** [comment]
Have you found a solution? I had the same problem

**Comment by andrasgalli** [comment]
Unfortunately: no :(

**Comment by evanmiller** [comment]
What version of unixODBC are you using?

**Comment by evanmiller** [comment]
We have many fixes to the ODBC driver in #162. This code has been tested on multiple platforms and so I encourage you to try it out to see if it fixes your issue.

**Comment by evanmiller** [comment]
It appears this issue was fixed in unixODBC 2.3.4:

https://sourceforge.net/projects/unixodbc/files/unixODBC/2.3.4/

As the problem seems to originate unixODBC I am closing the issue.

**Comment by edyulianto** [comment]
I still find this issue in macOs Catalina, I've installed :
mdbtools 0.7.1_3 
unixodbc 2.3.9
php 7.4.11

**internal error, unexpected SHLIBEXT value ('`test .$module = .yes && echo .so || echo .dylib`') may indicate a problem with configure
Abort trap: 6**

**Comment by evanmiller** [comment]
Please try the latest beta version:

https://github.com/mdbtools/mdbtools/releases

**Comment by zeyser** [comment]
Helped for me - https://github.com/yoramdelangen/laravel-pdo-odbc#504-bad-gateway-error
