### ISSUE TITLE
Unknown Jet version.

### ISSUE THREAD

**Issue by pcav** [mdbtools/mdbtools#151]
Attempting 
``mdb-tables DB.accdb ``
results in
``Unknown Jet version.
Couldn't open database.``
Is this a known limitation for newest Office versions, or something that I can fix?
Thanks a lot.

**Comment by evanmiller** [comment]
I believe this issue is fixed on the cyberemissary fork:

https://github.com/cyberemissary/mdbtools/commit/0e9c1810f17e27fdf0c40990b57a411c9113886d

**Comment by pcav** [comment]
Can the fix be merged back upstream?
Thanks.

**Comment by pcav** [comment]
I can confirm, it works. How about releasing a new version of mdbtools, @evanmiller ?

**Comment by evanmiller** [comment]
@pcav I am not an administrator on either repository but I am happy to participate in any discussion about getting mdbtools properly maintained.

**Comment by pcav** [comment]
Thanks for your positive response. I have opened a similar ticket on the updated repo:
https://github.com/cyberemissary/mdbtools/issues/17

**Comment by plin2** [comment]
I also need the fixed version

**Comment by pcav** [comment]
@plin2 for which OS/version?

**Comment by plin2** [comment]
Would be RHEL 7

**Comment by pcav** [comment]
sorry, non experience in packaging rpm. best would be to release a new upstream version, so distros could have their official packages.
anything we can do @brianb ?

**Comment by plin2** [comment]
mdbtools 0.7.1 is available in the EPEL repository. But 0.7.1 doesn't support newer Access versions. https://github.com/cyberemissary/mdbtools/releases seems to do the job.
I guess the EPEL guys will catch up when there is a newer master branch version available.

**Comment by evanmiller** [comment]
Fix included in #162. This will make its way to dev and master soon.

**Comment by pcav** [comment]
Great, thanks!

On 2 September 2020 02:50:07 CEST, Evan Miller <notifications@github.com> wrote:
>Fix included in #162. This will make its way to dev and master soon.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mdbtools/mdbtools/issues/151#issuecomment-685212311

-- 
Please excuse my brevity.

**Comment by plin2** [comment]
Thanks!
