### ISSUE TITLE
mdb-export -b octal produces some non-octal characters

### ISSUE THREAD

**Issue by ffishburn** [mdbtools/mdbtools#153]
I'm trying to export some binary data using the octal flag and there are non-octal codes being printed. It appears to me that the octal fprintf only gets called when the value is zero or negative, and putc gets called otherwise. Removing that condition (`*col_val <= 0`) appears to fix the issue.

https://github.com/brianb/mdbtools/blob/d6f5745d949f37db969d5f424e69b54f0da60b9b/src/util/mdb-export.c#L67-L68

**Comment by evanmiller** [comment]
Fix included in #162
