### ISSUE TITLE
SQL_DESC_UPDATABLE not provided by mdbtools ODBC driver

### ISSUE THREAD

**Issue by willbprog127** [mdbtools/mdbtools#156]
Greetings! :smile: 

I have been trying to use Free Pascal on Debian Linux to get data out of MS Access (.mdb) files.  The problem is that mdbtools' ODBC driver does not provide the SQL_DESC_UPDATABLE column attribute.  This makes Free Pascal's ODBC mechanism throw a big fat error.  I have temporarily modified the Free Pascal code to ignore the check for SQL_DESC_UPDATABLE, but this probably is not good a long-term solution.

It appears that the file needing the fix is `/src/odbc/odbc.c` around line 856 in the function `static SQLRETURN SQL_API _SQLColAttributes()`.  I don't have a firm grasp on ODBC internals, otherwise I'd create a pull-request for you.  Even if it just returned `SQL_ATTR_READWRITE_UNKNOWN` or `SQL_ATTR_READONLY` that would be fine.

Thank you! :+1: 

* Debian Linux 10
* MDB Tools 0.7.1-6
* Free Pascal 3.0.4

**Comment by evanmiller** [comment]
Included in #162, thanks for the contribution!
