### ISSUE TITLE
Unknown record type 2

### ISSUE THREAD

**Issue by myasarfr** [mdbtools/mdbtools#158]
When working with my MDB database (JET4) using any mdb tools (for example mdb-tables) I get many warnings : 'Unknown record type 2'

The record type '2' seems to contain property values, for example 'Replicable' or 'ReplicableBool'.

The following patch 'fixes' the warnings.

`--- a/src/libmdb/props.c`
`+++ b/src/libmdb/props.c`
`@@ -196,6 +196,7 @@ mdb_kkd_to_props(MdbHandle *mdb, void *buffer, size_t len) {`
` 				break;`
` 			case 0x00:`
` 			case 0x01:`
`+			case 0x02:`
` 				if (!names) {`
` 					fprintf(stderr,"sequence error!\n");`
` 					break;`

**Comment by evanmiller** [comment]
Included in #162, thanks for the contribution!
