### ISSUE TITLE
MDB-EXPORT with custom columns

### ISSUE THREAD

**Issue by ravikumargadagotti** [mdbtools/mdbtools#161]
This is more like a question, can I export custom or selected columns only using mdb-export utility?, if I need to use mdb-sql for this, then I am not able to get it working, I am getting an error "You must configure using --enable-sql to get SQL support", can anyone please help me how to get mdb-sql working, latest version of 0.7 has been installed and mdb-export is working fine.

**Comment by evanmiller** [comment]
Hi, to compile `mdb-sql` you will need to install Bison/yacc and flex.

https://www.gnu.org/software/bison/
https://github.com/westes/flex/
