### ISSUE TITLE
mdbtools python odbc access on Ubuntu 20.04

### ISSUE THREAD

**Issue by monetschemist** [mdbtools/mdbtools#171]
Really great to see this project alive and kicking again, thanks for that!

Trying to use MDBTools odbc to get at an .mdb file on Ubuntu 20.04, and I'm stumped:
- there is no libmdbcodbc on Ubuntu 20.04;
- there is libmdb2 and libmdbsql2, which seem to come from Debian

Having libodbc1, odbc-mdbtools, odbcinst, odbcinst1debian2, python3-pyodbc all installed, I can do this:

```
$ python3
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyodbc
>>> for d in pyodbc.drivers():
...     print(d)
... 
MDBTools
>>> 
```

So it looks as though I do have the driver and Python bits installed.

Moreover, mdb-tables tells me I have tables in my .mdb file:

```
$ mdb-tables *.mdb
FOREST_COVER_OBJECT GDB_ColumnInfo GDB_DatabaseLocks GDB_GeomColumns GDB_ItemRelationships GDB_ItemRelationshipTypes GDB_Items GDB_Items_Shape_Index GDB_ItemTypes GDB_ReplicaLog LAND_COVER_COMPONENT_EST NON_VEGETATIVE_COVER_EST SelectedObjects Selections SEQUENCE TRANSACTION TREE_COVER_LAYER_ESTIMATED TREE_SPECIES_ESTIMATED VEGETATION_COVER_POLYGON_EST FOREST_COVER_OBJECT_GEOMETRY_Index GDB_SpatialRefs 
$
```

However this idea (from pyodbc docs) fails:

```
$ python3
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyodbc
>>> 
>>> dbFile = '/home/me/test.mdb'
>>> odbcConnectionStr = 'DRIVER={MDBTools};DBQ=%s;' % (dbFile)
>>> connection = pyodbc.connect(odbcConnectionStr)
>>> cursor = connection.cursor()
>>> 
>>> for tableInfo in cursor.tables(tableType='TABLE'):
...     print(tableInfo.tableName)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x00 in position 12: truncated data

```

And a simple query bombs as well:

```
$ python3
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyodbc
>>> 
>>> dbFile = '/home/clh/Projects/TimberlineVRI/Revelstoke_Pre_Delineation_Final.mdb'
>>> odbcConnectionStr = 'DRIVER={MDBTools};DBQ=%s;' % (dbFile)
>>> connection = pyodbc.connect(odbcConnectionStr)
>>> cursor = connection.cursor()
>>> 
>>> cursor.execute('SELECT * FROM FOREST_COVER_OBJECT')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.Error: ('HY000', 'The driver did not supply an error!')
>>> 
```

Does anyone have any suggestions as to what might be failing here?  Do I need to use a DSN instead of a DBQ, or some other variation?

**Comment by nirgal** [comment]
You are looking for Debian package odbc-mdbtools I suppose. This naming convention is used by other odbc backends like mariadb and postgresql.

**Comment by nirgal** [comment]
I last used odbc with mdbtool some years ago.
My /etc/odbc.ini file is
```cat /etc/odbc.ini 
[india]
Description         = India
Driver              = MDBtools
Database = /home/nirgal/db.in/india/india.mdb

[ODBC]
Trace = 1
TraceFile = /tmp/odbctrace.log
Debug = 1
DebugFile = /tmp/odbcdebug.log
```
Also, I remember the unicode version was added recently, and not tested much. If you still have python2, you lay want to try it.

**Comment by mjwoodcock** [comment]
It looks like you need to set the character encoding of your connection:

connection = pyodbc.connect(odbcConnectionStr)
connection.setencoding('UTF-8')
connection.setdecoding(pyodbc.SQL_CHAR, encoding='UTF-8')
cursor = connection.cursor()

(Or whatever encoding your .mdb file uses).

That should get you further.

You will probably end up with an extra "0x00" on the end of all your strings.  I assume this is a bug with the libmdb ODBC driver.

**Comment by monetschemist** [comment]
@nirgal and @mjwoodcock thanks for your replies and sorry for my tardiness in responding.

I updated my first script with the setencoding() and setdecoding() ideas and that definitely helped.  I also discovered that the idea that the values returned by the cursor.tables(tableType='TABLE') are not dictionaries but rather tuples.  And as suggested there is indeed a trailing \x00 on every non-null string.  Here's what it looks like:

```
$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyodbc
>>> dbFile = '/home/me/test.mdb'
>>> odbcConnectionStr = 'DRIVER={MDBTools};DBQ=%s;' % (dbFile)
>>> connection = pyodbc.connect(odbcConnectionStr)
>>> connection.setencoding('UTF-8')
>>> connection.setdecoding(pyodbc.SQL_CHAR, encoding='UTF-8')
>>> cursor = connection.cursor()
>>> for tableInfo in cursor.tables(tableType='TABLE'):
...     print(tableInfo)
... 
(None, None, 'MSysObjects\x00', 'SYSTEM TABLE\x00', None, None, None, 'MSysObjects\x00', 'SYSTEM TABLE\x00', None)
(None, None, 'MSysACEs\x00', 'SYSTEM TABLE\x00', None, None, None, 'MSysACEs\x00', 'SYSTEM TABLE\x00', None)
(None, None, 'MSysQueries\x00', 'SYSTEM TABLE\x00', None, None, None, 'MSysQueries\x00', 'SYSTEM TABLE\x00', None)
(None, None, 'MSysRelationships\x00', 'SYSTEM TABLE\x00', None, None, None, 'MSysRelationships\x00', 'SYSTEM TABLE\x00', None)

etc

>>> 
```
Regrettably, replacing the "for" loop at the end with

`cursor.execute('SELECT * FROM MSysObjects')`

continues to yield 

```
Traceback (most recent call last):
  File "testodbc2.py", line 8, in <module>
    cursor.execute('SELECT * FROM MSysObjects')
pyodbc.Error: ('HY000', 'The driver did not supply an error!')

```
So I'm not a great deal further ahead.  At least, I don't think I am.  Perhaps it's those pesky trailing nulls.

Anyway, thanks for the suggestions.  I take it this odbc driver is not a part of this mdbtools initiative?

**Comment by mjwoodcock** [comment]
I don't get that error.

cursor.execute("SELECT * from MSysObjects")
rows = cursor.fetchall()
for row in rows:
    print(row)

works on my database file, at least.

Can you attach your test database do this issue?

I have a fix for the trailing nulls, I will try and get that submitted over the next few days.

**Comment by monetschemist** [comment]
@mjwoodcock I can definitely share this MDB.  It's quite large however - 64MB unzipped, 23 zipped.  Might it be better putting in say Google Drive and sharing the link?

**Comment by mjwoodcock** [comment]
Yeah, Google drive would work.

But you might be better off building MDBTools from source.  I suspect that the Ubuntu version is rather out of date, and you will probably end up waiting a long time for a new version.  Don't forget to build from the dev branch.

**Comment by evanmiller** [comment]
@monetschemist If you want to build from source, we have fairly recent beta download available:

https://github.com/mdbtools/mdbtools/releases/tag/v0.9.0-beta1

**Comment by monetschemist** [comment]
Thanks, everyone.  I will build from source sometime over the weekend and give it a whirl.  @evanmiller would you prefer I use the beta version, or the dev branch (I'm fine with either)?

**Comment by monetschemist** [comment]
@evanmiller after I wrote the above I thought "why not now", so I grabbed the v.0.9.0-beta1, added bison, flex, gawk and unixodbc-dev (version 2.3.6) from my Ubuntu 20.04 repos, did the autoreconf -i -f, ./configure --with-unixodbc=/dev/local and finally make.

The make failed as follows:

```
make[2]: Entering directory '/home/clh/src/mdbtools-0.9.0-beta1/src/odbc'
  CC       unittest.o
  CC       odbc.lo
odbc.c:29:10: fatal error: mdbodbc.h: No such file or directory
   29 | #include "mdbodbc.h"
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:513: odbc.lo] Error 1
```

Any thoughts on where I might find mdbodbc.h?

**Comment by evanmiller** [comment]
@monetschemist Looks like a bug in the beta build - I'll put out a new beta later today for you to test with.

**Comment by evanmiller** [comment]
@monetschemist Please try Beta 2 here: https://github.com/mdbtools/mdbtools/releases/tag/v0.9.0-beta2

**Comment by monetschemist** [comment]
@evanmiller I removed the previous version, untarred, did the autoreconf -i -f, the./configure --with-unixodbc=/usr/local and finally make.  Failed as follows:
```

Making all in doc
make[1]: Entering directory '/home/clh/src/mdbtools-0.9.0-beta2/doc'
./txt2man -t mdb-tables -r "MDBTools 0.9.0-beta2" -s 1 -v "Executable programs or shell commands" ./mdb-tables.txt > mdb-tables.1
/bin/sh: 1: ./txt2man: not found
make[1]: *** [Makefile:606: mdb-tables.1] Error 127
make[1]: Leaving directory '/home/clh/src/mdbtools-0.9.0-beta2/doc'
make: *** [Makefile:479: all-recursive] Error 1
```

I found a txt2man in the Ubuntu20.04 repos, installed it, deleted the install directory, untarred again, did the autoreconf and ./configure again in the new install directory, issued the make.  Same error message.

Seems I am missing a local thing called "txt2man"?

**Comment by evanmiller** [comment]
Thanks - another bug. Try configuring with `--disable-man`.

**Comment by nirgal** [comment]
Regarding the extra \0, there is a patch at https://github.com/mjwoodcock/mdbtools/commit/c609f5b5a66c0d334525d1db6b6d3717c3bc6cbb that may be what we are looking for

**Comment by monetschemist** [comment]
@evanmiller really sorry for the lengthy delay!

Built fine with ./configure --disable-man -with-unixodbc=/usr/local

I needed to do sudo ldconfig to sort that.

I don't know how much of a test you want, but I decided to take a quick look at mdb-sql first.  Two things I noticed right away:

1. there is a line feed (and should not be, I think) after every prompt, for example:

```
$ mdb-sql *.mdb
1 => 
list tables
2 => 
go
```
Also, I get an error with the list tables command:

```
warning: row_size = 0.
warning: mdb_find_row failed.
```

which does not happen in the older version.

On the Python end of things, I'm not sure how to tell Python to use the new version of the stuff.  For reference, my test Python script looks like:

import pyodbc
dbFile = '/home/clh/Projects/TimberlineVRI/Revelstoke_Pre_Delineation_Final.mdb'
odbcConnectionStr = 'DRIVER={MDBTools};DBQ=%s;' % (dbFile)
connection = pyodbc.connect(odbcConnectionStr)
connection.setencoding('UTF-8')
connection.setdecoding(pyodbc.SQL_CHAR, encoding='UTF-8')
cursor = connection.cursor()
for tableInfo in cursor.tables(tableType='TABLE'):
  print(tableInfo)

**Comment by evanmiller** [comment]
Hi, this issue is all over the place, so I am closing it. If you continue to experience issues with the [0.9.0 release](https://github.com/mdbtools/mdbtools/releases/tag/v0.9.0), please open a separate GitHub issue for each one (e.g., line feed, list tables, Python compatibility, etc)

**Comment by evanmiller** [comment]
@monetschemist The extra newline issue is fixed in https://github.com/mdbtools/mdbtools/commit/31d8bc13aa5abc2e11969dbf7ebb1396e489c801
