### ISSUE TITLE
Getting error with large mdb file 

### ISSUE THREAD

**Issue by hemanth-sp** [mdbtools/mdbtools#172]
when I execute in ubuntu python3 (and this works fine if I have a small MDB file with one table)

```
table_names = subprocess.Popen(["mdb-tables", "-1", DATABASE], 
                               stdout=subprocess.PIPE).communicate()[0]
```

its giving error  like
```
read: Is a directory
Couldn't read first page.
Couldn't open database.

```

**Comment by evanmiller** [comment]
What version of MDB tools? Can you share the file?

**Comment by hemanth-sp** [comment]
i don't the version, below is my zip file
[SmartOffice.mdb.zip](https://github.com/mdbtools/mdbtools/files/5331473/SmartOffice.mdb.zip)

**Comment by evanmiller** [comment]
Hi, this file opens fine for me using the latest `dev` code.

I notice that your first error is `read: Is a directory`. Are you sure you're passing the correct path?

**Comment by hemanth-sp** [comment]
yes,

**Comment by evanmiller** [comment]
Please try one of the 0.9 beta releases and see if that fixes your issue:

https://github.com/mdbtools/mdbtools/releases

**Comment by evanmiller** [comment]
If you experience issues using the 0.9 beta, please create a new issue with a link to the file that will not open. Thanks.
