### ISSUE TITLE
The postgres backend to mdb-export gets the TIMESTAMP format wrong

### ISSUE THREAD

**Issue by monetschemist** [mdbtools/mdbtools#176]
I've been using mdb-export to convert my MDB files to PostgreSQL INSERT statements using

`mdb-export -I postgres -q "'" database-name table-name`

and I notice that the TIMESTAMP format produced by this export appears to be incorrect.

According to [this PostgreSQL documentation page](https://www.postgresql.org/docs/12/datatype-datetime.html) the supported formats for TIMESTAMP follow "the ISO 8601 standard", for example:

`1999-01-08 04:05:06`

or "the common format"

`January 8 04:05:06 1999 PST`

What mdb-export produces is

`'04/20/06 12:08:06'`

To work around this, I filter my output with sed as follows:

`sed 's/\([01][0-9]\)\/\([0123][0-9]\)\/\([0-9][0-9]\)/20\3-\1-\2/g'`

(I can get away with this because my dates are all in 2000+)

**Comment by mjwoodcock** [comment]
./mdb-export -T "%Y-%m-%d %H:%M:%S" database-name table-name

should give you the output you require if you don't want to use sed.

I know how to fix this in the code, so I'll hopefully submit a patch over the weekend.

**Comment by monetschemist** [comment]
@mjwoodcock it seems I don't have a -T option.  I'm using the version supplied in the Ubuntu 20.04 repos which is 0.7.1-6build1.

**Comment by evanmiller** [comment]
Fixed in 0.9.0 Beta 3: https://github.com/mdbtools/mdbtools/releases/tag/v0.9.0-beta3
