### ISSUE TITLE
libraries calls exit

### ISSUE THREAD

**Issue by nirgal** [mdbtools/mdbtools#181]
This is a very old design bug, that has not be documented yet, I believe:

libmdb and libmdbsql calls the C library exit() or _exit().
This is not the proper way to handle a fatal error, including out of memory or similar conditions.

The library should return NULL or an error code or something, but it should not kill the caller process under any circumstances.

**Comment by evanmiller** [comment]
Thanks for flagging this - agree 100%.

**Comment by evanmiller** [comment]
The exits from libmdbsql might require some `setjmp` skulduggery to work around:

https://stackoverflow.com/questions/30341967/flex-yy-fatal-error-exist-just-like-that-i-want-handler-back-to-application

**Comment by evanmiller** [comment]
I believe the only remaining exits are when certain SQL parser functions are called without an input buffer. I don't think there's anything else that can be done here without serious acrobatics, so I am closing the issue.
