### ISSUE TITLE
Files over 2GB are not supported on i386 arch, we must force 64bits file offset there

### ISSUE THREAD

**Issue by nirgal** [mdbtools/mdbtools#190]
The original bug report is [here](https://bugs.debian.org/888045).

Basically, on 32 bits architectures, we do use 32 bits file offsets.
We should use -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE on the compiler.

There may be issues after that.

It might be as simple as adding AC_SYS_LARGEFILE in configure.ac

**Comment by evanmiller** [comment]
Probably needs to replace `fseek` with `fseeko` as well. Will make a pull request for you to test.
