### ISSUE TITLE
[Feature request] Ignore warnings flag for mdb-sql 

### ISSUE THREAD

**Issue by andreiFiodorov** [mdbtools/mdbtools#191]
Hi all, thank you guys for these tools. I have installed the beta version "0.9.0, Beta 3" to have the possibility to make SQL queries.

I'm using exec command from node.js child process and I want to ignore warning messages.
At moment the warning messages put them in `stderr`. 

Thanks!

**Comment by evanmiller** [comment]
Can you redirect `stderr` inside Node.js? I'm afraid the warning messages are scattered throughout the code base so it will be a non-trivial effort to consolidate them for suppression.

**Comment by andreiFiodorov** [comment]
I have the solution to avoid the warning message. If adding a flag to ignore warning messages is a non-trivial effort I'm close the issue.
