### ISSUE TITLE
Tag 0.9.0-beta7 not availavle with git-fetch

### ISSUE THREAD

**Issue by keestux** [mdbtools/mdbtools#202]
This tag is at commit https://github.com/mdbtools/mdbtools/commit/226c822e990d6288f2fdc89671d7e1c25ec7e110 and if you click on it, you'll see

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

However you won't get it if you do a git-fetch

**Comment by evanmiller** [comment]
Fixed
