### ISSUE TITLE
A list of How much of the Access SQL lang is supported.

### ISSUE THREAD

**Issue by P-Medicado** [mdbtools/mdbtools#203]
When using the `mdb-sql` tool in *mdbtools-0.9.0-beta7* which features of SELECT are supported?
Any tests that fail are strictly `Error at Line : syntax error`

Of course, there is a good repo providing Jet support for **EntityFramework Core**. If `mdbtools` can replicate the read-syntax well enough, using Access as a cross platform web database backend will be drop-in compatible with SQLite, MySQL, SQL Server, etc (at least in read ability which is a great achievement).

> SELECT * FROM Parts;
**Star:** ✔️ 

> SELECT COUNT(*) FROM Parts;
**Count:** ✔️ 

> SELECT COUNT(Sku) FROM Parts;
**Count:** ❌ 

> SELECT Name AS FullName FROM Employees;
**AS:** ❌  

> SELECT \`Full Name\` FROM EmployeesQuery;
**Backtick \`:** ❌ 
**Handling Spaces:** ❌ 

If this test was conducted incorrectly or you would like more info let me know here or via the twitter linked account.

**Comment by evanmiller** [comment]
Hi, I don't think there's a formal list anywhere but you can take a peek at the grammar file for clues:

https://github.com/mdbtools/mdbtools/blob/dev/src/sql/parser.y

Feel free to open specific feature requests as separate issues, and hopefully someone will take a look at them before too long.

**Comment by P-Medicado** [comment]
Thanks @evanmiller the lexer.l file gave an overview of which keywords are supported at the basic level. Full "Jet compliance", probably, isn't a requirement for EF Core SQL generators. With the current lexer showing understanding of `where`, `top`, `like`, `list tables`, `describe table table_name`,

most likely, SQL generators like EFCore Jet would run with support added for 

1. `table AS t` / `column AS c` 
2. \` supporting backticks like: 
> SELECT * FROM \`table with space\` 

These two syntax features are specifically critical to C# LINQ or other means of SQL generation at runtime. Issue 203 is only a request for a *list* of supported SQL features, not these two features in particular. A markdown table may work for README.MD, still this is all specific to the `mdb-sql` tool, not to mdbtools as a whole.

**Comment by evanmiller** [comment]
Hi, turns out the man page documents the supported SQL features:

https://github.com/mdbtools/mdbtools/blob/dev/doc/mdb-sql.txt

I've just updated it to include the newer TOP and LIMIT support.

Since this appears to answer your question, I am closing the issue. If you'd like to see additional SQL features added, please open a separate issue for each one.
