### ISSUE TITLE
HTML / SGML files are out of date

### ISSUE THREAD

**Issue by evanmiller** [mdbtools/mdbtools#207]
These files appear to be out of date:

* [doc/install.sgml](https://github.com/mdbtools/mdbtools/blob/dev/doc/install.sgml)
* [doc/faq.html](https://github.com/mdbtools/mdbtools/blob/dev/doc/faq.html)
* [doc/reference/libmdb/libmdb-docs.sgml](https://github.com/mdbtools/mdbtools/blob/dev/doc/reference/libmdb/libmdb-docs.sgml)
* [doc/reference/libmdb/libmdb-sections.txt](https://github.com/mdbtools/mdbtools/blob/dev/doc/reference/libmdb/libmdb-sections.txt)

They should be updated or removed before 0.9.0. If removed, we can excise everything related to gtk-doc from the Makefiles.

**Comment by evanmiller** [comment]
Removed from Beta 8. If you think any of these files should be restored, leave a note here.

**Comment by pedromorgan** [comment]
We could set up a doxygen action to create api.docs from source

**Comment by evanmiller** [comment]
@pedromorgan That would be great

**Comment by pedromorgan** [comment]
Ok so gonna setup doxygen.. so expect patch...

can't do the gh-pages etc part.. 
- Q is with actions can it end up at mdbtools.github.io/mdbtools

Is the same caper as I do on gitlab with openplc.. and "inter doxygen"..
.. https://openplcproject.gitlab.io/openplc_v3/

Only thing I can recommend/suggest/enforce is to use doxygen, even for main www.site...
were in C land right ??

Whats always "pisses me off" is having two sets of install et all, detached from the source... 

- so a "patch" will involve updating the docs also would be perfect..
- and into master.. and site rebuilt et all..
