### ISSUE TITLE
Source location has moved

### ISSUE THREAD

**Issue by terryh-j** [mdbtools/mdbtools#209]
Building files for source fails with the following error: 
Failure while downloading http://www.gnome.org/~veillard/gamin/sources/gamin-0.1.10.tar.gz

It seems that Garmin files have moved from http://www.gnome.org/~veillard/gamin/sources/gamin-0.1.10.tar.gz to https://people.gnome.org/~veillard/gamin/sources/ and the PKGBUILD file needs editing.

**Comment by evanmiller** [comment]
Hi, I think you have the wrong project, or at least a very old version. This is MDB Tools, a library for reading Access files. It does not use Gamin.
