### ISSUE TITLE
Driver's SQLAllocHandle on SQL_HANDLE_HENV failed 

### ISSUE THREAD

**Issue by kasra-keshavarz** [mdbtools/mdbtools#210]
Hello,

This the versions of the my system components:

- python: 3.8.0
- pyodbc: 4.0.30
- unixodbc: 2.3.9
- mdbtools: 0.7.1

I have compiled everything by myself and installed stuff locally on a HPC cluster. here is my local odbcinst.ini:

> [kak136@platolgn01 mdbtools]$ cat ~/LocalSoftware/etc/odbcinst.ini
> [mdbtools]
> Description=MDBTools driver for MS Access files *.mdb
> Driver=/home/kak136/LocalSoftware/lib/libmdb.so
> Setup=/home/kak136/LocalSoftware/lib/libmdb.so
> FileUsage=1
> UsageCount=1

and here is the odbc.ini:

> [example]
> Driver = mdbtools
> Description = checking a library
> Database = /demand_scripts/ssrab_v21OUTPUT.mdb
> Server = localhost

here is a list of my local libraries compiled:

`aclocal.m4    AUTHORS         build-aux   config.status  configure.ac  COPYING.LIB  HACKING  libmdb.pc     libmdbsql.pc     libtool  Makefile     Makefile.in  README     src
appveyor.yml  autom4te.cache  config.log  configure      COPYING       doc          include  libmdb.pc.in  libmdbsql.pc.in  m4       Makefile.am  NEWS         README.md  TODO`

when I try to open a sample .mdb file I get this error:
`[kak136@platolgn01 mdbtools]$ python
Python 3.8.0 (default, Nov 12 2019, 19:43:25)
[GCC 5.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyodbc
>>> dbFile = './ssrab_v21OUTPUT.mdb'
>>> odbcConnectionStr = 'DRIVER={mdbtools};DBQ=%s;' % (dbFile)
>>> connection = pyodbc.connect(odbcConnectionStr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.Error: ('IM004', "[IM004] [unixODBC][Driver Manager]Driver's SQLAllocHandle on SQL_HANDLE_HENV failed (0) (SQLDriverConnect)")`

**Comment by evanmiller** [comment]
Hi, there will be many improvements to the ODBC driver in the 0.9.0 release. You can download a beta or wait for the final release here:

https://github.com/mdbtools/mdbtools/releases

**Comment by kasra-keshavarz** [comment]
I tried the version `0.9.0` released minutes earlier and still get the same error.

**Comment by evanmiller** [comment]
@kasra-keshavarz I think the mistake is in your INI file. The driver should be `libmdbodbc.so`, not `libmdb.so`.

**Comment by txemaquintero** [comment]
Hi,

I have the same issue, but on a different environment. I'm using on Mac OS 10.15.7 Catalina with PDO_ODBC PHP.

I have installed all using Home Brew:

brew install unixodbc
brew install mdbtools

and this is my odbcinst.ini

[MDBTools]
Description = MDBTools Driver
Driver = /usr/local/lib/libmdb.dylib
Setup  = /usr/local/lib/libmdb.dylib
FileUsage = 1
UsageCount = 1

I was searching for the file **libmdbodbc.dylib** but I couldn't find it, also I tried with **libodbc.dylib** but with the same error:

_Fatal error: Uncaught PDOException: SQLSTATE[IM004] SQLDriverConnect: 0 [unixODBC][Driver Manager]Driver's SQLAllocHandle on SQL_HANDLE_HENV_

Thanks for your help.

**Comment by evanmiller** [comment]
@txemaquintero The mdbtools ODBC driver is not installed by Homebrew. Please see #146 for additional instructions.

**Comment by txemaquintero** [comment]
Hi!

I followed the guide on #146 and now I have this error:

**internal error, unexpected SHLIBEXT value ('`test .$module = .yes && echo .so || echo .dylib`') may indicate a problem with configure**

I'm using unixodbc 2.3.9

Thanks for your help.

**Comment by evanmiller** [comment]
@txemaquintero When does this error appear? If it is after a `brew` step, it may indicate an issue with homebrew.

**Comment by txemaquintero** [comment]
Hi,

I have modified the mdbtools.rb using **brew edit mdbtools** and after that the error appear.

I will try to do all the installation process, but not using HomeBrew and keep informed you.

Thanks for your help.

**Comment by evanmiller** [comment]
Because the original issue appears to be a configuration error, I am closing this issue.
