### ISSUE TITLE
Using (external) libmswstr to create index fields via Jet 4 driver

### ISSUE THREAD

**Issue by rhurlin** [mdbtools/mdbtools#215]
Looking into [src/libmdb/index.c](https://github.com/mdbtools/mdbtools/blob/60ee6495b71abb910e7abe9c58dae6dbf9731e40/src/libmdb/index.c), the Jet 4 driver seems to prefer using the **function DBLCMapStringW** from external libmswstr [1].

Are there any experiences or opinions about using the external dependency for this?

I am asking, because after the release of MDBtools 0.9.0 I am preparing the update of the FreeBSD port [2] and would like to know whether it makes sense to include the library as a dependent.

[1] [leecher1337/libmswstr](https://github.com/leecher1337/libmswstr)
[2] [FreeBSD Port databases/mdbtools](https://www.freshports.org/databases/mdbtools)

**Comment by evanmiller** [comment]
Hi,

`MDB_USE_INDEX` is off by default – according to the thread in https://github.com/evanmiller/mdbtools/pull/26, indexes do not work properly for strings. However, it's quite possible the tester in that thread simply needed the libmswstr library to get string support working, as the code comment indicates that string indexes are useless without it:

https://github.com/mdbtools/mdbtools/blob/60ee6495b71abb910e7abe9c58dae6dbf9731e40/src/libmdb/index.c#L62-L67

The issue needs more research and I welcome any other perspectives on this. The existing index code was essentially ignored for 0.9.0 release.

**Comment by evanmiller** [comment]
I'll also note that this commit

https://github.com/mdbtools/mdbtools/commit/e9ec53f6bd36517b7fafb1a2531bba8d026e0431

States "Used as a separate library to do it like MS Jet and to ensure that mdbtools library doesn't get tainted with its source."

The explanation is in the [COPYING](https://github.com/leecher1337/libmswstr/blob/master/COPYING) file:

```
I had to reverse engineer the mswstr.dll in order to get the translation 
tables. Unless someone uses the information gathered by reading this library
to write a proper library with a proper license.
So I guess I can't claim copyright for this code.
Therefore regarding license I can just say: Take it or leave it.
```

I think pulling out translation tables is probably a copyright-safe thing to do, but I guess @leecher1337 wanted to avoid any hints of impropriety. In any event, for purposes of FreeBSD I think either we say the copyright is okay and pull the code into MDB Tools, or say it's not okay and leave libmswstr out of ports / distributions.

**Comment by rhurlin** [comment]
Hi Evan,

> `MDB_USE_INDEX` is off by default – according to the thread in [evanmiller#26](https://github.com/evanmiller/mdbtools/pull/26), indexes do not work properly for strings. However, it's quite possible the tester in that thread simply needed the libmswstr library to get string support working, as the code comment indicates that string indexes are useless without it:
> ...
> The issue needs more research and I welcome any other perspectives on this. The existing index code was essentially ignored for 0.9.0 release.

Many thanks for the explanation. I have a local, working version of `libmswstr` and could do some testing with `mdbtools-0.9.0`.

I must confess that I do not understand the exact syntax. What must the call to mdbtools look like so that I can test indexes (with and without `libmswstr`; with and without environment variable set)?

If tests with the indexes turn out well, I would ask in the FreeBSD community whether the code of libmswstr is acceptable under licensing law.

**Comment by evanmiller** [comment]
> I must confess that I do not understand the exact syntax. **What must the call to mdbtools look like** so that I can test indexes (with and without `libmswstr`; with and without environment variable set)?

`libmswstr` is detected at configure-time, look for something like

```
checking for DBLCMapStringW in -lmswstr
```

In the mdbtools configure log. It cannot be turned on and off with flags, so you may need to tweak your header and library search paths to flip it on and off.

On the environment variable, you'll want to set

```
MDBOPTS=use_index
```

To enable index support on any running code. I would ask @nyalldawson for test cases / test files. I'm not sure whether all MDB files are indexed, or only some.

**Comment by nyalldawson** [comment]
Indeed I didn't have libmswstr available when I did my testing. But this looks a bit problematic for a number of reasons:
1. We should either disable the attempt to use indexes for strings when the library isn't available OR make libmswstr a compulsory dependancy for enabling index support. Otherwise users silently get broken results (as I did initially!)
2. libmswstr isn't widely available. I can't see any packages available for any Linux distro, for instance. 
 

I think we should revisit the library seperation decision - it would certainly be much cleaner from a code/user perspective to have it included here and allow indexing support by default.

**Comment by rhurlin** [comment]
Hi Nyall,

> Indeed I didn't have libmswstr available when I did my testing. But this looks a bit problematic for a number of reasons:
> 
>     1. We should either disable the attempt to use indexes for strings when the library isn't available OR make libmswstr a compulsory dependancy for enabling index support. Otherwise users silently get broken results (as I did initially!)
> 
>     2. libmswstr isn't widely available. I can't see any packages available for any Linux distro, for instance.
> 
> 
> I think we should revisit the library seperation decision - it would certainly be much cleaner from a code/user perspective to have it included here and allow indexing support by default.

I agree that it would be good (and necessary) to integrate the functionality of libmswstr. Of course, before that it should be clarified if it works. 

I would like to do some tests with mdbtools for this. On FreeBSD I have a (local) working port for libmswstr, I can build MDBtools against it and then run some tests. 

But what would be the concrete syntax for mdbtools binaries to work with (and test) the indexes of mdb files? Could you show some examples, how to use mdbtools for that?

Many thanks in advance.

**Comment by rhurlin** [comment]
> `libmswstr` is detected at configure-time, look for something like
> 
> ```
> checking for DBLCMapStringW in -lmswstr
> ```

Yup, in my configure.log it looks like 
```
configure:16689: checking for DBLCMapStringW in -lmswstr
configure:16714: cc -o conftest -O2 -pipe  -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing  -I/usr/ports/databases/mdbtools/work/mdbtools-0.9.0/include -DLIBICONV_PLUG -I/usr/local/include  -L/usr/local/lib -fstack-protector-strong  conftest.c -lmswstr   >&5
configure:16714: $? = 0
configure:16723: result: yes
```
and later
```
ac_cv_func_index=yes
ac_cv_lib_mswstr_DBLCMapStringW=yes
```

> In the mdbtools configure log. It cannot be turned on and off with flags, so you may need to tweak your header and library search paths to flip it on and off.
> 
> On the environment variable, you'll want to set
> 
> ```
> MDBOPTS=use_index
> ```

Does it really only works on running code, when MDBOPTS=use_index is set at runtime?

> To enable index support on any running code. I would ask @nyalldawson for test cases / test files. I'm not sure whether all MDB files are indexed, or only some.

I asked Nyall about it in the hope, he has some examples how to test it :)

**Comment by evanmiller** [comment]
> Does it really only works on running code, when MDBOPTS=use_index is set at runtime?

Yes.

**Comment by nyalldawson** [comment]
My testing was really quite rudimentary -- I simply set MDBOPTS=use_index and tried querying some text fields using mdb-sql, and noticed that no results were ever returned! (I was originally planning on adding unit tests for indexing as a precursor to enabling indexes by default, but stopped when I mistakenly concluded that the index support was just a broken experimental feature)

**Comment by evanmiller** [comment]
I invite everyone in this discussion to try out #226, which automatically enables indexes for JET3 databases, and when libmswstr is present. (You can also force indexes with `use_index`, as before.)

**Comment by evanmiller** [comment]
According to the document here:

ftp://178.213.241.33/Soft/Science%20Tools/Statistica%207/English/SYSUP/eulamdac.txt

`mswstr10.dll`, from which libmswstr is derived, is a "redistributable component" that carries with it certain non-compete restrictions. So I think the legal question would be the degree to which libmswstr is derived from the copyrightable essence of `mswstr10.dll`.

**Comment by rhurlin** [comment]
> My testing was really quite rudimentary -- I simply set MDBOPTS=use_index and tried querying some text fields using mdb-sql, and noticed that no results were ever returned! (I was originally planning on adding unit tests for indexing as a precursor to enabling indexes by default, but stopped when I mistakenly concluded that the index support was just a broken experimental feature)

Thanks Nyall,
For your answer.

All I can say ATM is, that with libmswstr linked in and env MDBOPTS=use_index set, I am able to read in all types of data from mdb files, even if the field is indexed. The data appears complete and correctly coded.

What I can't manage with mdbtools is to query for a table, if and for which fields an index exists.

**Comment by evanmiller** [comment]
I've added a new warning about the libmswstr requirement for `use_index`. Until the index code receives proper test coverage, I will be treating it as experimental and unsupported, and I do not recommend including it in distributions.

To graduate from experimental status, we will need:

* Clarification about the copyright status of libmswstr
* Confirmation that `use_index` works with non-ASCII data in JET3 databases (doubtful)
* Test coverage for both JET3 and JET4 databases

I don't see this getting resolved in the immediate future, so I am closing this issue. I welcome further contributions in this area, but I believe that the current discussion about indexes has run its course. Feel free to open a PR if you have any specific improvements to the index support that you would like to see merged.

If anyone decides to become the champion for indexes – with the goal of having it graduate to become a tested and supported feature – then we can open a tracking issue.
