### ISSUE TITLE
mdbtools returns integer column values as a truncated string when retrieved via binding

### ISSUE THREAD

**Issue by Stephano2000** [mdbtools/mdbtools#23]
For a long integer column (4 bytes):
- SQLGetData with type = integer will return the data as a 4 byte integer (OK)
- SQLGetData with type = char will return the data as a string (OK?)
- SQLBindCol with type = char will return the data as a string (OK?)
- SQLBindCol with type = integer will return 4 chars which represent the 1st 4 ascii codes of the integer (BUG). For example, the value 100123 will be returned as 0x31, 0x30, 0x30, 0x31 rpresenting '1001', instead of 100123 as a 4 byte integer.
  I have traced this to _mdb_attempt_bind in data.c which treats BOOL types correctly, but defers all other types to mdb_xfer_bound_data which in turn treats MDB_NUMERIC types in one way, and all remaining types (including INTEGER, BYTE, etc...) as string.

**Comment by evanmiller** [comment]
@nyalldawson This might be an interesting one for you.

**Comment by evanmiller** [comment]
Should be fixed in #242 (and 🤞 in the upcoming 0.9.2 release)
