### ISSUE TITLE
Add --version and/or -v option to display program version

### ISSUE THREAD

**Issue by rob-hills** [mdbtools/mdbtools#232]
It's pretty much a universal standard (amongst 'nix programs anyway) for a program to print out its current version number and exiting in response to the -v and/or --version command-line option.

Could this be added to one (or ideally all) of the mdb- tools?

**Comment by evanmiller** [comment]
You can retrieve the current version with `mdb-ver -M`

**Comment by pedromorgan** [comment]
Ok so reading between the lines..
we need a definitive...`mdb-tickle` command
- or `mdb-commander` or alike

So a can query , list etc
and enter commander mode with all sort of capers...

- show tables
- contacts show columns

Cos there's a lot of apps atmo... but also understand 200% why its done that way..

**Comment by pedromorgan** [comment]
I just see a practical tool to use... quick and fast etc

- mdb-tickle --read-only --quick-view //mafia-family/caerrole-stew/don/2021-pandemic-office/clients-current.mdb
- mdb-tickle --out-excel "ohh_dear.xml" --tables=family|banks|mobiles|offshore //mafia-fa-etc...t.mdb

**Comment by evanmiller** [comment]
Added in https://github.com/mdbtools/mdbtools/commit/f99c5539e7ee228b2ef9021f881262ece214a7f0

**Comment by evanmiller** [comment]
Fixed in 0.9.2.
