### ISSUE TITLE
mdb-export problem when exporting relations with CREATE TABLE

### ISSUE THREAD

**Issue by chrgm** [mdbtools/mdbtools#236]
When I want to export a database file with relations and indexes to a PostgreSQL using:

> mdb-export database.mdb postgres | psql -d dbname

I run into a problem with relations between the tables, when the command tries to create a relation to a table that isn't created at that point. 
Therefore I first use it in the following order:

> mdb-export database.mdb postgres --no-relations | psql -d dbname
> mdb-export database.mdb postgres | psql -d dbname

There I first create all tables and then run the second command to add the relations. This leads to the errors that the tables already exist. (quite obvious)
Is there something I oversee, or am I using mdb-export wrong?

If not, it would be an idea to add an option to either to add `CREATE TABLE IF NOT EXISTS` or remove the `CREATE TABLE` part with a parameter.

**Comment by evanmiller** [comment]
Hi, thanks for the report. It sounds like a bug in the exporter. The commands should be ordered so that the relationships are established after all of the relevant tables have been created.

**Comment by chrgm** [comment]
Sorry for that issue is was a mistake of my setup. 
The commands I posted in the issue can't work and were unfortunately messed up by me when writing it.
I read again through my scripts and found the problem.
Of course the command orders the relationships in the correct way.
So everything is fine.

The only thing where I stuck is with the foreign key contrains.
- I create the schemas with `mdb-schema ${FILE} postgres | psql -d ${DB}`
- I add the data with 
> mdb-tables -1 ${FILE} | while read -r table; do
> mdb-export -I postgres -q "'" -D "%F" -T "%F %T" -B ${FILE} "${table}" | psql -d ${DB}`
> done

But then I run into problems with foreign key constrains that aren't met when adding data. Are there any tips?
