### ISSUE TITLE
When will the latest major version be released to APT for Debian? 

### ISSUE THREAD

**Issue by kiernann** [mdbtools/mdbtools#241]
I'm working on a small project that uses `apt install mdbtools` to facilitate usage of this package (especially in continuous integration via GitHub Actions). I would love to be able to make use of the latest features like `--boolean-words` that don't appear in v0.7.1 found on APT.

**Comment by evanmiller** [comment]
Hi, Debian bullseye will include MDB Tools 0.9.1

https://packages.debian.org/testing/mdbtools
