### ISSUE TITLE
question: configure --with-unixodbc=/usr/local

### ISSUE THREAD

**Issue by kalpha2** [mdbtools/mdbtools#243]
when doing the configure e.g.
`configure --with-unixodbc=/usr/local`
is the "/usr/local" where it expects something or is where something is going to be built into? 
For a standard Debian 10 which has unixodbc and unixodbc-dev installed how do you determine if /usr/local is appropriate?
I can't find where unixodbc is installed but can find isql in "/usr/bin"

**Comment by evanmiller** [comment]
Try `--with-unixodbc=/usr`

**Comment by kalpha2** [comment]
can you clarify is the --with-unixodbc needed for input to and or the output of the configure and is it critical to be in sync with where the standard debian repo install of it's unixodbc is?

**Comment by evanmiller** [comment]
Hi,

If the isql is in /usr/bin then you will use `./configure --with-unixodbc=/usr`

Yes you will need to point to the Debian location of unixODBC.
