### ISSUE TITLE
odbc.ini Driver setting for mdbtools in Debian

### ISSUE THREAD

**Issue by kalpha2** [mdbtools/mdbtools#245]
this may be a debian or a unixodbc question but as it seemingly pertains specifically to mdbtools (for me) I ask here if any thoughts.
the unixodbc instructions say the odbc.ini Driver parameter should relate to a section name in the odbcinst.ini file e.g. the standard debian 10 or 11 repo install puts in odbcinst.ini the following
`[MDBTools]`
`Description=MDBTools Driver`
`Driver=libmdbodbc.so`
`Setup=libmdbodbc.so`
`FileUsage=1`
`UsageCount=1`

and that I should have something like the following in an odbc.ini (I've tried the /etc and local version)
`[MyTest]`
`Description = MyTest`
`Driver = MDBTools`
`Servername = localhost`
`Database = /home/user01/Northwind.mdb`
`Name =`
`Password =`
`port = 5432`

But isql fails to connect. However if I change the odbc.ini Driver setting to point to the driver file directly e.g.

`Driver=/usr/lib/x86_64-linux-gnu/odbc/libmdbodbc.so
`
isql works fine. 

for reference this is only affecting mdbtools if I try the suggested format for e.g. sqlite it works as expected.

**Comment by evanmiller** [comment]
Thanks for the report. See #116

**Comment by kalpha2** [comment]
ah, is #116 supposed to give me clue to allow the odbcinst entry to work as Drive in odbc.ini?
It appears to suggest it is working ... wondering if it means I have to run the odbcinst command as in that thread?
But I'm not sure where the `mdbodbcinst.ini`
it references is to be found? or does it have to be crafted based on the entries as already present in the debian repo installed creation of /etc/odbcinst.ini

**Comment by nirgal** [comment]
The script at https://salsa.debian.org/debian/mdbtools/-/blob/master/debian/odbc-mdbtools.postinst is executed by package odbc-mdbtools with parameter "configure" on installation.

Debian has a special hack to install libmdbodbc.so in "odbc" subfolder of the (arch dependant) librairies, like /usr/lib/x86_64-linux-gnu/odbc/.

**Comment by kalpha2** [comment]
ta, still not sure why the odbc.ini Driver setting doesn't work using the odbcinst.ini name ... but pointing direct the driver .so works.
