### ISSUE TITLE
interface to mdbtools from pure c

### ISSUE THREAD

**Issue by kalpha2** [mdbtools/mdbtools#246]
so I'm trying to craft a simple console test program to call an installed mdbtools. I took the gmdb2 main2.c and took out all of the Gnome related stuff and brought in the 
> gmdb_file_open

from the gmdb2 file.c file also removing gnome related code. When I initially tried to build it complains around a list of dependencies that must be needed by mdbtools as they are not referenced in the above, so I have got to the below

> 
gcc main.c -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gtk-2.0 -I/usr/include/cairo/ -I /usr/include/pango-1.0/ -I /usr/lib/x86_64-linux-gnu/gtk-2.0/include/ -I /usr/include/gdk-pixbuf-2.0/ -I /usr/include/atk-1.0/

but it complains about not finding the below

> 
main.c:(.text+0x19): undefined reference to 'mdb_open'
/usr/bin/ld: main.c:(.text+0x42): undefined reference to 'mdb_set_default_backend'
/usr/bin/ld: main.c:(.text+0x56): undefined reference to 'mdb_read_catalog'

I've found them in the mdbtools source and I have mdbtools-dev repo package installed and given the not finding glib2 etc I assume it must be finding mdbtools so why can't it find these within mdbtools?

**Comment by evanmiller** [comment]
You will need to link to libmdb. Try adding

`-lmdb`

**Comment by kalpha2** [comment]
ta, that worked.
so the line 
`mdb = mdb_open(file_path, MDB_NOFLAGS);`

does not report error but when I 

`	mdb_read_catalog(mdb, MDB_TABLE);
	i = mdb->num_catalog;
	printf("Number of tables: %i\n",i);`

if says zero tables, I'm passing it Northwind.mdb so know that is not the case. Or have I misunderstood this?

**Comment by evanmiller** [comment]
I would check the return value of `mdb_read_catalog` - it should be non-zero if successful.

**Comment by kalpha2** [comment]
`    GPtrArray *gptrA = mdb_read_catalog(mdb, MDB_TABLE);
    printf("mdb_read_catalog return pointer: %i\n",gptrA[0]);`

returns
`mdb_read_catalog return pointer: -537897184
`

**Comment by kalpha2** [comment]
So something to do with the building ...
I've looked at mdb-tables.c if I attempt to build with 
`gcc -o myTestMdb-Tables mdb-tables.c -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gtk-2.0 -I/usr/include/cairo/ -I /usr/include/pango-1.0/ -I /usr/lib/x86_64-linux-gnu/gtk-2.0/include/ -I /usr/include/gdk-pixbuf-2.0/ -I /usr/include/atk-1.0/ -I /media/sdd02/src/mdbtools/include/ -I /media/sdd02/src/mdbtools/include/ -lmdb -lglib-2.0`

It builds and runs, but I get no output. If I rebuild with 
`i = mdb->num_catalog; printf("Number of tables: %i\n",i);`

that says zero tables.

If I rerun the full mdbtools make the rebuilt mdb-tables now tells me it sees 103 tables (and other objects) and shows the list of tables. 

So I guess the Makefile brings in something that is neither essential for building or being able to run but is needed to actually interrogate an mdb correctly.

**Comment by kalpha2** [comment]
to confirm it, I moved my test code into /mdbtools/src/util and hacked the Makefile in there to build it ... and it runs as expected. So now I just need to suss what is needed to build a satellite utility that makes use of an installed mdbtools

**Comment by kalpha2** [comment]
sorry for the noise .. issue was caused by me linking to local build of mdbtools from current source but using (old) mdbtools libs as installed by Debian repo (on Debian 10)

**Comment by kalpha2** [comment]
couple more questions so will re-open (is there a mailing list or forum that is better to "ask" questions?
So I have been progressing with a basic example c program and now looking at the mdb sql side of things.
I've lifted some code from mdb-sql.c including the routine 
`dump_results_pp(FILE *out, MdbSQL *sql)`

where it fails on the line 
`print_value(out, (char *) g_ptr_array_index(sql->bound_values, j), sqlcol->disp_size,!j);`

with 
`error: request for member ‘pdata’ in something not a structure or union
`
and it points to 
`g_ptr_array_index`

Is there another reference I need for the "pdata" ... I've done a quick search but not found it in code or google.

Also I attempted to build the same code on Debian 11 Bullseye but encounter this 
`/usr/include/mdbtools.h:37:10: fatal error: mdbfakeglib.h: No such file or directory
   37 | #include <mdbfakeglib.h>
`
Any thoughts?

**Comment by kalpha2** [comment]
So I will open a new issue regarding the mdbfakeglib.h on Debian 11 Bullseye and will close this one soon as I have progressed but still have a question... 
to get past the `error: request for member ‘pdata’ in something not a structure or union`

I have just replaced   `print_value(out, (char *) g_ptr_array_index(sql->bound_values, j), sqlcol->disp_size,!j);`

with  `print_value(out, (char *) sql->bound_values[j], sqlcol->disp_size,!j);`

and seems to work ... so just curious what benefit if it worked would  `g_ptr_array_index`   would give me?

**Comment by kalpha2** [comment]
my previous changes resulted in an error on Debian 11 once I added the -DHAVE_GLIB to get past another error.
I reverted these changes on Debian 11 and it then built and ran as expected.
But adding the -DHAVE_GLIB to the Debian 10 didn't seem to have an effect and I still could not use the g_ptr_array_index
