### ISSUE TITLE
fatal error: mdbfakeglib.h:  mdbtools from Debian 11 repo

### ISSUE THREAD

**Issue by kalpha2** [mdbtools/mdbtools#247]
if I pull mdbtools 0.9.1 from Debian standard repo for Debian Bullseye (11) and attempt to build a simple c program that interfaces to mdbtools I get on the building 
`/usr/include/mdbtools.h:37:10: fatal error: mdbfakeglib.h: No such file or directory
   37 | #include <mdbfakeglib.h>`

(which does not happen on Debian 10 which has mdbtools 0.7.x from the Debian repo)

NB I have pulled the 0.9.1 source from here and builds all okay, so presume there is some artefact missing from the Debian repo version of /usr/include/mdbtools.h or something it (should) reference?

**Comment by nirgal** [comment]
Hello

Make sure you have the dependencies installed. If you are running Debian 11, you can just run

> apt-get build-dep mdbtools

Or manually install all the packages listed in the Build-Depends section of https://tracker.debian.org/media/packages/m/mdbtools/control-0.9.1-1

Alternatively, maybe the build from debian 11 works with debian 10 (not tested):

> git clone https://salsa.debian.org/debian/mdbtools.git
> cd mdbtools
> debuild
> cd ..
> sudo dpkg -i libmdb3_0.9.1-1_amd64.deb libmdbsql3_0.9.1-1_amd64.deb mdbtools_0.9.1-1_amd64.deb ...

You could also replace the git clone by
> dget -x https://deb.debian.org/debian/pool/main/m/mdbtools/mdbtools_0.9.1-1.dsc

These two last methods have the advantage to have debuild reporting if you are missing some dependencies...

**Comment by evanmiller** [comment]
@kalpha2 You need to compile your program with the same flags that went into compiling mdbtools. Try adding `-DHAVE_GLIB`

**Comment by kalpha2** [comment]
@evanmiller thank you, with -DHAVE_GLIB it no longer encountered the mdbfakeglib.h error.
I then got an errors 
`error: incompatible types when initializing type ‘char *’ using type ‘GPtrArray’`
`error: cannot convert to a pointer type`

these were on the changes I made to make it work on Deb10 by replacing e.g.
`print_value(out, (char *) g_ptr_array_index(sql->bound_values, j), sqlcol->disp_size,!j);`

with
`print_value(out, (char *) sql->bound_values[j], sqlcol->disp_size,!j);`

so I just reverted and all working as expected now
