### ISSUE TITLE
support for wildcard symbols in mdb?

### ISSUE THREAD

**Issue by kalpha2** [mdbtools/mdbtools#249]
I've seen #233 and curious the opening comment has `select * from table where column like '%dummy%'`
was that specific or psuedo example?
I'm asking because I've tried when connecting to Northwind.mdb the `select * from Shippers` 
lists the three records including one e.g. CompanyName of "United Package"
if I do `select * from Shippers where CompanyName like '%Pack%'` 
runs the query but shows zero records.
I also tried using * instead of % but same result.
I'm running these through unixODBC isql for now.

**Comment by evanmiller** [comment]
Hi, 0.9.1 has a bug where string literals are incorrectly interpreted. This will be fixed in 0.9.2. Feel free to download a beta from the Releases page and test it out.

**Comment by kalpha2** [comment]
so I did `git pull`
on my copy of folder I did `git clone`
but when I do ./configure now I get 
`configure: MDB Tools 0.9.2-beta3 - Configuration summary`
`configure:    ODBC            : disabled`
all others are enabled. 
NB I have v0.9.1 installed from repo and it runs through isql fine so I presume dependencies should be fine.
What can I look for?

**Comment by nirgal** [comment]
You should read the README file :p

**Comment by kalpha2** [comment]
indeed ... I forgot the --with-unixodbc parameter ... so next ... i have done a make but not make install because I have and want to keep the repo installed mdbtools for now. So I have attempted the following I created a new entry in the local .odbc.ini of a new section of
`[myTestB]`
`Driver=/media/sdd02/src/mdbtools-deb11/src/odbc/.libs/libmdbodbc.so`
and the usual other entries, should this work, running isql myTestB connects and runs the original queries (in this thread) but has the same results. Is there a command I can run in isql to confirm it is using the updated version of libmdbodbc.so ?

**Comment by kalpha2** [comment]
so I think I have worked out mdb-sql but it is still cannot get wildcards to work
if I do  `./mdb-sql --version`   I get   `mdbtools v0.9.2-beta1`
Then 
`./mdb-sql -i testSqlIn3.txt -o testSqlOut3.txt ~/Northwind.mdb `
where testSqlIn3.txt contains 
`select * from Shippers where CompanyName Like '%Pack%'`
and the result in testSqlOut3.txt contains
`+-----------+----------------------------------------+------------------------+`
`|ShipperID  |CompanyName                             |Phone                   |`
`+-----------+----------------------------------------+------------------------+
+-----------+----------------------------------------+------------------------+`
`No Rows retrieved`

**Comment by evanmiller** [comment]
@kalpha2 The bug is fixed in `v0.9.2-beta3`  - looks like it's finding beta1?

**Comment by kalpha2** [comment]
@evanmiller  thank you. did another `.git pull`  build it now shows version beta3 and works as desired via both mdb-sql and isql
