### ISSUE TITLE
making small change and hacking link

### ISSUE THREAD

**Issue by kalpha2** [mdbtools/mdbtools#252]
So I would like to make the following small change 

--- a/src/libmdb/write.c
+++ b/src/libmdb/write.c
@@ -273,7 +273,8 @@ mdb_crack_row(MdbTableDef *table, int row_start, size_t row_size, MdbField *fiel
                        fields[i].is_null = 1;
                }
                if ((size_t)(fields[i].start + fields[i].siz) > row_start + row_size) {
'-                       fprintf(stderr, "warning: Invalid data location detected in mdb_crack_row.\n");
'+                       //fprintf(stderr, "warning: Invalid data location detected in mdb_crack_row.\n");
'+                       fprintf(stderr, "warning: Invalid data location detected in mdb_crack_row. Table:%s Column:%i\n",table->name, i);

What are the steps I need to take? Do I need to create a fork and then commit to it?

also from the bottom of first page (code) on Github it has a link for hacking which takes you to a page that says 
it's been moved and see  

> https://github.com/mdbtools/mdbtools/blob/master/HACKING.md

but that comes back as a dead link?

**Comment by evanmiller** [comment]
@kalpha2 You have a couple of options for small changes.

1. Make a fork, commit to it, and open a pull request against the `dev` branch
2. Edit the file directly via GitHub by navigating to it and clicking the Edit icon in the top right (Pencil icon 🖊)

Please do not include commented-out lines in the pull request.

The HACKING link will be fixed in the final 0.9.2 release.

**Comment by kalpha2** [comment]
as it was just a one line change I went with option 2, it says

> This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests.

So do I need to do anything else?
What does the "Close pull request" button do? Am I supposed to hit it, or does that effectively say forget the commit?

separate question is there some easy way to get the column name? Where is mdbfield structure defined? I was looking for hopefully could make use of a field[i].name ..... or ilk??

**Comment by evanmiller** [comment]
You don't need to do anything else; I will merge your pull request into the repository. (Closing it will cancel the request.)

Almost all of the structure used internally and externally are defined here

https://github.com/mdbtools/mdbtools/blob/dev/include/mdbtools.h

**Comment by kalpha2** [comment]
@evanmiller cool.
