### ISSUE TITLE
mdbtools odbc segmentation fault when reading specific numeric fields

### ISSUE THREAD

**Issue by uclaros** [mdbtools/mdbtools#255]
On a specific mdb, I am getting a segmentation fault when reading values from numeric fields.

I initially opened an issue in OSGeo/gdal#3455 but I can reproduce the issue with isql.
The offending mdb is https://github.com/OSGeo/gdal/files/5976019/file.zip

In `isql`:
- `select * from bad_table` gives a segfault.
- `select * from bad_table where 1=2` returns the headers
- selecting text fields works ok
- selecting numeric fields segfaults

Reading the file without odbc works fine, ie `mdb-export file.mdb bad_table` works fine

**Comment by nyalldawson** [comment]
I can take a look at this tomorrow 👍

**Comment by pedromorgan** [comment]
rock on @evanmiller ;-)))
