### ISSUE TITLE
mdb-export error: offset 24826077184 is beyond EOF

### ISSUE THREAD

**Issue by voidplayer** [mdbtools/mdbtools#259]
```
$ mdb-export file.mdb bigtextfieldtable
[...]
offset 24826077184 is beyond EOF
```

**Comment by evanmiller** [comment]
Can you share the file?

**Comment by voidplayer** [comment]
Unfortunately file have data that is illegal for to me share. Is there an easy way to anonymize it?

**Comment by kalpha2** [comment]
@voidplayer  easy way to anonymize - probably not. But if you are familiar with the structure and content of the MDB, if it is just one particular table you could export it to a new mdb ... check it still fails with mdb-export and if so you could then use use MS Access or VB to craft code to update each row with replacement data ... check again with mdb-export to confirm it still fails and then make that available.

**Comment by evanmiller** [comment]
@voidplayer Without an example file there's nothing that we can do. "Anonymizing it" will require creating a file with a different tool.

**Comment by voidplayer** [comment]
@kalpha2 i dont have access to MS access

@evanmiller Well, it will discard if the problem is with the content :)

It exports okay the first ~3000 fields. Its a table with big text fields. I will take a look how can i give more info to make this reproducible

Is there a verbose mode that i can use to show the fields its trying to export? Or the error is in the reading?

**Comment by evanmiller** [comment]
@voidplayer Try setting the environment variable `MDBOPTS=debug_all` for more debugging information. e.g.

```
env MDBOPTS=debug_all mdb-export file.mdb bigtextfieldtable
```

**Comment by kalpha2** [comment]
Hi @evanmiller do you think we know if this is message from write.c or file.c ?
1. Do you think there is merit changing 
   fprintf(stderr,"offset %" PRIu64 " is beyond EOF\n",(uint64_t)offset);
   to in file.c
   fprintf(stderr,"offset %" PRIu64 " is beyond EOF in _mdb_read_pg\n",(uint64_t)offset);
   and in write.c
   fprintf(stderr,"offset %" PRIu64 " is beyond EOF in mdb_write_pg\n",(uint64_t)offset);
   
2. Is there any mileage in outputting the value of ftello(mdb->f->stream) in the message? 

3. Does this message mean the start of the page is beyond the EOF or that the length overlaps? If the latter would it be possible and or make any sense to read from the start of page to the EOF? And if necessary pad the returned page? If not highlight the error but not stop the output of what has been retrieved? Do we suspect this is a corrupted db not a code issue?

**Comment by voidplayer** [comment]
@evanmiller debug output attached [export_debug.txt](https://github.com/mdbtools/mdbtools/files/6091344/export_debug.txt)

Sorry it took me so long

**Comment by evanmiller** [comment]
@kalpha2 To address your points

1 - Probably adding `__FILE__` and `__LINE__` to the messages would be useful. In this case, the message is almost certainly from _mdb_read_pg since we are reading the file and not writing to it.

2 - Adding the output of `ftello` would help give context in cases like this one, for sure (lets us know the file size)

3 - The beginning of the requested page is beyond EOF, so padding tricks won't help here. The file appears to be quite large so without the file itself I don't know whether it's a corrupt DB or a coding error.

**Comment by voidplayer** [comment]
2. File size is 32 mdb with 168 tables. Only this one table give this error
3. Ive been busy these days. Im still figuring out how can i anonymize the file. I know that would be the easier than second guessing here

**Comment by kalpha2** [comment]
@evanmiller Shall I craft 1 and 2? re 3. Does the export do it's job to that point or does it abort?
@voidplayer Do you know if the mdb was used across a network by possibly multiple users? If it is corrupted you probably need  a suitable version Access to check and confirm. You also would need that and a copy of VB to be able to anonymise it which would still be quite a work and if it is corrupted they may not let you ....

**Comment by voidplayer** [comment]
@kalpha2 not used across a network and i cant tell if its corrupted, but i think is not

That table is special compared to the rest because is saving big chunks of text. Altering the tables with access or VB will also alter the file. I can also try to debug it myself using the source code to see exactly what makes it bork. I dont know what is easier (and if im capable)

Im guessing this ```row_vaoffset 24826077184 is beyond EOF``` is part of a sanity check

**Comment by evanmiller** [comment]
@kalpha2 Sure, a pull request would be useful. You'll have to ask @voidplayer how much of the export occurs before terminating.

@voidplayer Somewhere a bad page number is being processed. Likely something in the file is being read as a page number that shouldn't be. One hypothetical example is if Access uses some sort of special extra-large page to store big text and the usual page boundaries don't apply. It will be hard to know without digging into the file binary.

**Comment by evanmiller** [comment]
Closing for lack of an example file. If you can share a file that produces the error message, please open a new issue.
