### ISSUE TITLE
Problem reading .accdb file (Unknown Jet version: 6)

### ISSUE THREAD

**Issue by jayadevanm** [mdbtools/mdbtools#260]
I am trying to open a .accdb file. I tried the latest version of mdbtools and building. But I keep getting the error 
```
Unknown Jet version: 6
Could not open file
```
Version of mdbtools - 
```
mdb-ver --version
mdbtools v0.9.2-beta6
```
Operating system - Ubuntu 20.10, 64 bit.

**Comment by evanmiller** [comment]
Hi, can you share the file that's not opening?

**Comment by jayadevanm** [comment]
Hi, Sorry, I can't. It is an accessdb shared by a client. I do suspect it is a problem with the file. I faced a similar issue with Easysoft driver too.

**Comment by evanmiller** [comment]
Hi, do you know what version of Access created the file?

**Comment by evanmiller** [comment]
Hi, please see if your file can be opened with this code branch:

https://github.com/mdbtools/mdbtools/tree/access-2019

**Comment by jayadevanm** [comment]
Yes, that worked.
