### ISSUE TITLE
v0.9.2 prints warnings about mdb_col_to_string on FreeBSD

### ISSUE THREAD

**Issue by rhurlin** [mdbtools/mdbtools#262]
Thank you for the important update. Really appreciated.

Because of the security issues, as maintainer of the **MDBTools port for FreeBSD** [1], I immediately updated the port to the new version. Unfortunately, there are problems with the new version on FreeBSD that did not occur with v0.9.1, which prevents me from committing the update ;(

[1] https://www.freshports.org/databases/mdbtools

With a very simple database Datenbank1.mdb, created MS Access 2013, containing only one table Tabelle1 with three columns and two rows, I get the following output:

**With v0.9.1 this example runs fine:**
```
# MDBTools v0.9.1
>mdb-tables Datenbank1.mdb 
Tabelle1

>mdb-export Datenbank1.mdb Tabelle1
ID,text1,number1
1,"example1",3264
2,"example2",
```

**With v0.9.2 this example prints warnings `about mdb_col_to_string`:**
```
# MDBTools v0.9.2
>mdb-tables Datenbank1.mdb 
Warning: mdb_col_to_string called on an unsupported data type.
Tabelle1

>mdb-export Datenbank1.mdb Tabelle1
Warning: mdb_col_to_string called on an unsupported data type.
ID,text1,number1
1,"example1",3264
2,"example2",
```
The database itself and the debug output of `mdb-export Datenbank1.mdb Tabelle1` is attached in the zip file:
[Datenbank1.zip](https://github.com/mdbtools/mdbtools/files/6055011/Datenbank1.zip)

More complex databases with more columns and rows generate many more similar warnings before the content is output.

Even more surprising for me is that there are also databases that do not generate such warnings.

Since I have to work a lot with mdb files from third party vendors, I cannot influence the way the file is generated.

And as I said, these warnings did not occur with v0.9.1. Do you have any idea what's going on? I would be happy to provide more information or perform further tests. Thanks in advance!

**Comment by evanmiller** [comment]
Hi, the change in behavior is likely due to this commit:

https://github.com/mdbtools/mdbtools/commit/1bfce353d4ee3de10a6346b1c616a12d510320d2

I will be able to investigate in more detail later.

**Comment by rhurlin** [comment]
> Hi, the change in behavior is likely due to this commit:
> 
> [1bfce35](https://github.com/mdbtools/mdbtools/commit/1bfce353d4ee3de10a6346b1c616a12d510320d2)

Hi Evan, Thanks for the pointer.


I have extended the `fprintf` to output `datatype`: 

```
fprintf(stderr, "Warning (default): mdb_col_to_string called on an unsupported data type: %d \n", datatype);
```

Now I get:

```
#mdb-tables Datenbank1.mdb
Warning (default): mdb_col_to_string called on an unsupported data type: 11 
Tabelle1
``` 
If I am right, data type 11 should be 'OLE' from src/libmdb/backend.c? That seems odd.

So is it possible that the numerical order of `datatype` in `data.c` does not match the order in `backend.c`? Just a guess ;)

**Comment by evanmiller** [comment]
@rhurlin That's correct; type 11 is OLE as defined here:

https://github.com/mdbtools/mdbtools/blob/dev/include/mdbtools.h#L112

The order doesn't matter as `[MDB_OLE]` will fill in the 11th (zero-indexed) slot of the C array.

We'll need to figure out the code path where this is being called, as it "shouldn't" happen (using quotes as this is an inherited code base and I am still trying to understand all the internal logic). I believe that OLE fields should not be using this function, but it will take some more research to figure out why this is happening.

**Comment by rhurlin** [comment]
I have very little knowledge with C/C++, but  just try to get a bit familiar with lldb, llvm's debugger. 
MDB Tools is built here on my FreeBSD box with clang 11.0.1. This is what I get until now:

```
#lldb /usr/local/bin/mdb-tables Datenbank1.mdb

(lldb) target create "/usr/local/bin/mdb-tables"
Current executable set to '/usr/local/bin/mdb-tables' (x86_64).
(lldb) settings set -- target.run-args  "Datenbank1.mdb"

(lldb) breakpoint set --file data.c --line 1050
Breakpoint 1: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.

(lldb) r
Process 27539 launching
Process 27539 launched: '/usr/local/bin/mdb-tables' (x86_64)
1 location added to breakpoint 1
Process 27539 stopped
* thread #1, name = 'mdb-tables', stop reason = breakpoint 1.1
    frame #0: 0x0000000800256422 libmdb.so.3`mdb_col_to_string(mdb=0x0000000800e5a000, buf=0x0000000801400eb5, start=56, datatype=11, size=258) at data.c:1053:12
   1050			default:
   1051				/* shouldn't happen.  bools are handled specially
   1052				** by mdb_xfer_bound_bool() */
-> 1053				fprintf(stderr, "Warning: mdb_col_to_string called on an unsupported data type.\n");
   1054				text = g_strdup("");
   1055			break;
   1056		}

(lldb) thread backtrace all
* thread #1, name = 'mdb-tables', stop reason = breakpoint 1.1
  * frame #0: 0x0000000800256422 libmdb.so.3`mdb_col_to_string(mdb=0x0000000800e5a000, buf=0x0000000801400eb5, start=56, datatype=11, size=258) at data.c:1053:12
    frame #1: 0x000000080026181b libmdb.so.3`mdb_read_props(mdb=0x0000000800e5a000, names=0x0000000800e1a660, kkd="\U00000006", len=470) at props.c:142:6
    frame #2: 0x00000008002612d4 libmdb.so.3`mdb_kkd_to_props(mdb=0x0000000800e5a000, buffer=0x0000000801400900, len=2094) at props.c:210:13
    frame #3: 0x0000000800251519 libmdb.so.3`mdb_read_catalog(mdb=0x0000000800e5a000, objtype=-1) at catalog.c:149:21
    frame #4: 0x0000000000202a6e mdb-tables`main(argc=2, argv=0x00007fffffffd650) at mdb-tables.c:149:8
    frame #5: 0x00000000002020b0 mdb-tables`_start + 256
```

Obiviously `mdb_col_to_string` (thread #0) is called here with **dataype 11** from `props.c:142.6` (thread #2), and so on. 

No idea if this is already useful for you? Please let me know if you want me to investigate further in a particular direction.

**Comment by evanmiller** [comment]
Thanks, this backtrace is very helpful. It should be enough for me to make some progress.

**Comment by evanmiller** [comment]
Hi, please see if this issue is fixed for you in the `dev` branch.

**Comment by rhurlin** [comment]
> Hi, please see if this issue is fixed for you in the `dev` branch.

Thanks for the patch. Unfortunately, with https://github.com/mdbtools/mdbtools/commit/46a65b9789e1668c626aa435c198c8593cdb4285 I get:

```
libtool: compile:  cc -DPACKAGE_NAME=\"mdbtools\" -DPACKAGE_TARNAME=\"mdbtools\" -DPACKAGE_VERSION=\"0.9.2\" "
-DPACKAGE_STRING=\"mdbtools 0.9.2\"" -DPACKAGE_BUGREPORT=\"https://github.com/mdbtools/mdbtools/issues\" 
-DPACKAGE_URL=\"https://github.com/mdbtools/mdbtools\" -DPACKAGE=\"mdbtools\" -DVERSION=\"0.9.2\" 
-DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 
-DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 
-DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DYYTEXT_POINTER=1 
-DSTDC_HEADERS=1 -DHAVE_FCNTL_H=1 -DHAVE_LIMITS_H=1 -DHAVE_UNISTD_H=1 -DHAVE_XLOCALE_H=1 
-DHAVE_WORDEXP_H=1 -DHAVE_LIBMSWSTR=1 -DHAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME=0 
-DHAVE_LIBREADLINE=1 -DHAVE_READLINE_READLINE_H=1 -DHAVE_READLINE_HISTORY=1 
-DHAVE_READLINE_HISTORY_H=1 -DHAVE_STRPTIME=1 -DHAVE_FMEMOPEN=1 -DHAVE_GMTIME_R=1 
-DHAVE_REALLOCF=1 -DHAVE_WCSTOMBS_L=1 -DHAVE_VASPRINTF=1 -DHAVE_ICONV=1 
-DICONV_CONST= -DHAVE_ATTRIBUTE_ALIAS=1 -DSIZEOF_LONG_INT=8 -DHAVE_LONG_LONG=1 
-I. -I/usr/ports/databases/mdbtools-dev/work/mdbtools-0.9.2-4-g46a65b9/include -DLIBICONV_PLUG 
-I/usr/local/include -I../../include -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include 
-I/usr/local/include -DHAVE_GLIB=1 -Wsign-compare -O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong 
-fno-strict-aliasing -DSQL -Wall -Werror -DUNIXODBC -MT data.lo -MD -MP -MF .deps/data.Tpo -c data.c  
-fPIC -DPIC -o .libs/data.o 
data.c:1010:5: error: format specifies type 'int' but the argument has type 'long' [-Werror,-Wformat]
                                mdb_get_int32(buf, start));
                                ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
*** Error code 1
Stop.
make[4]: stopped in /usr/ports/databases/mdbtools-dev/work/mdbtools-0.9.2-4-g46a65b9/src/libmdb

```

It seems, it stumbles over `mdb_get_int32(buf, start)` of the `MDB_COMPLEX` switch case?

**Comment by evanmiller** [comment]
@rhurlin Thanks, I've pushed another update to address the compile error.

**Comment by rhurlin** [comment]
> @rhurlin Thanks, I've pushed another update to address the compile error.

It seems with https://github.com/mdbtools/mdbtools/commit/ad8c80892b55e946e6e681f10dfe9c352bda94d7 it is fixed now. MDB Tools builds and installs fine on FreeBSD and first tests with several databases and tables work as expected. More tests will follow tomorrow ...

It is likely that this issue #262 is solved now. Many thanks!  \o/

**Comment by thesamesam** [comment]
@rhurlin Did you have a chance to test some more?

**Comment by rhurlin** [comment]
> @rhurlin Did you have a chance to test some more?

I don't have standardized tests that systematically check different data types, encodings, and linkages.

But I have been able to test the current version https://github.com/mdbtools/mdbtools/commit/ad8c80892b55e946e6e681f10dfe9c352bda94d7 in production use with much more complex databases in the meantime and everything seems to be ok :)

From my point of view this issue can be closed now.

**Comment by jaredbeck** [comment]
I see this has been resolved (thanks) and I have a follow-up question. I get the same stderr warning with 0.9.2 on macOS 11.2. It seems `mdb-export --date-format` no longer has any effect. (I get the same stdout with and without `--date-format`) Could that be related? Thanks.

**Comment by evanmiller** [comment]
@jaredbeck They are likely unrelated. You may also want to try the `--datetime-format` option. If it still doesn't work, please open a separate issue describing expected and actual behavior.

**Comment by jaredbeck** [comment]
> You may also want to try the --datetime-format option

Thanks Evan, I think that's what I was missing. It seems my previous version, 0.7.1 did not have this option.
