### ISSUE TITLE
./configure: line 12586: AC_LIB_PREPARE_PREFIX: command not found

### ISSUE THREAD

**Issue by huangchinlin** [mdbtools/mdbtools#263]
[environment]
ubuntu 20.04.1 desktop x86_64
mdbtools-0.9.2.tar.gz

[issue]
get error when run ./configure --with-unixodbc=/usr

./configure: line 12586: AC_LIB_PREPARE_PREFIX: command not found
./configure: line 12587: AL_LIB_RPATH: command not found
./configure: line 12592: syntax error near unexpected token `iconv'
./configure: line 12592: `           AL_LIB_LINKFLAGS_BODY(iconv)'

iconv, gettext and gettext-base those are installed.

Could help to advise is other required libraries here need to be installed before configure? Thanks.

**Comment by evanmiller** [comment]
Hi, did you run `autoreconf` yourself? (This step is unnecessary if you download the tar.gz package.)

**Comment by huangchinlin** [comment]
> Hi, did you run `autoreconf` yourself? (This step is unnecessary if you download the tar.gz package.)

yes, I ran `autoreconf` but situation is no change.
is' it possible relating to hardware platform? the environment to this is on Arm64 / Raspberry Pi4b / Unbuntu 20.04.

**Comment by evanmiller** [comment]
@huangchinlin I mean - Try downloading the tar.gz, then immediately run configure (do not run autoreconf)

**Comment by huangaixiu** [comment]
hello,I have meet this problem,did you solve it?
