### ISSUE TITLE
mdb-export bug: Truncation of Long Text (Memo) fields

### ISSUE THREAD

**Issue by mnizol** [mdbtools/mdbtools#267]
mdb-export appears to truncate Long Text (Memo) fields that exceed ~16,000 characters.

**Comment by evanmiller** [comment]
What version of MDB Tools are you using? I believe this was reported in #118 and fixed in #137 (i.e. resolved in 0.9.0)

**Comment by mnizol** [comment]
Thanks.  I installed via `apt` on Ubuntu.  The version available from their repository is 0.7.1-6build1.

**Comment by evanmiller** [comment]
Okay - this issue is fixed in the 0.9.0 series, which you can install from source. You can also download a .deb file of 0.9.1 from this page:

https://packages.debian.org/bullseye/mdbtools
