### ISSUE TITLE
Publish 0.9.2 Please

### ISSUE THREAD

**Issue by roansong-span** [mdbtools/mdbtools#270]
I have managed to build the latest library from source, but it would be much much easier for me and my deployments if I could get it straight from `apt`. Thanks!

**Comment by pedromorgan** [comment]
So this means creating either:

- as PPA ?
- or other means

Could u explain what "platform".. is it docker ?

**Comment by nirgal** [comment]
Debian is currently [frozen](https://release.debian.org/bullseye/freeze_policy.html), pending its new release.
Next "stable" release of mdbtools will be 0.9.1.
Version 0.9.2 is available as an official .deb file in experimental. https://tracker.debian.org/pkg/mdbtools
You can get the .deb files from the snapshots (second icon on the right of "versions"), but there might be dependencies you don't like, like very recent libc.
As soon as Debian 11 is out, 0.9.2 will make its way to "testing".

Most Debian derivative, like Ubuntu, are based on "testing". They will automatically upgrade to 0.9.2 when Debian does. You can check [here](https://launchpad.net/ubuntu/+source/mdbtools) for 0.9.1 for Ubuntu.
I'm not familiar with Mint and other derivative, unfortunately.

In my experience, the Debian freeze is quite long, and I would not expect the new version until this summer. But it's definitely coming.

**Comment by roansong-span** [comment]
Thank you very much for the info! I'll look at either pulling from experimental or packaging a version internally.
