### ISSUE TITLE
A couple of fixes to write.c

### ISSUE THREAD

**Issue by HenriHakonen** [mdbtools/mdbtools#271]
My version is write.c and  WRITE.C.ORIGINAL is release 0.9.2.
1. This way fwrite returns length:
***** write.c
        fseeko(mdb->f->stream, offset, SEEK_SET);
        len = fwrite(mdb->pg_buf, 1, mdb->fmt->pg_size, mdb->f->stream);
        if (ferror(mdb->f->stream)) {
***** WRITE.C.ORIGINAL
        fseeko(mdb->f->stream, offset, SEEK_SET);
        len = fwrite(mdb->pg_buf, mdb->fmt->pg_size, 1, mdb->f->stream);
        if (ferror(mdb->f->stream)) {
*****

2. mdb_crack_row takes size instead of end:
***** write.c
        }
        num_fields = mdb_crack_row(table, row_start, old_row_size, fields);
    if (num_fields == -1) {
***** WRITE.C.ORIGINAL
        }
        num_fields = mdb_crack_row(table, row_start, row_end, fields);
    if (num_fields == -1) {
*****

**Comment by evanmiller** [comment]
Thanks! Would you mind opening a pull request for each suggested change? Pull requests help us keep track of contributions and when bugs are fixed or introduced. You should be able to do it easily on this page:

https://github.com/mdbtools/mdbtools/edit/dev/src/libmdb/write.c

**Comment by evanmiller** [comment]
Fixed in #272
