### ISSUE TITLE
Brew uses --enable-sql, but mdb-sql disagrees

### ISSUE THREAD

**Issue by jaredbeck** [mdbtools/mdbtools#273]
## The Homebrew [formula](https://github.com/Homebrew/homebrew-core/blob/341e0d7d9f865dfd6015c17ca9d1baeeab8a2f32/Formula/mdbtools.rb) passes `--enable-sql` to `./configure`

```plain
brew reinstall --build-from-source mdbtools
..
==> Installing mdbtools
==> autoreconf -fvi
==> ./configure --prefix=/usr/local/Cellar/mdbtools/0.9.2 --enable-sql --enable-man
==> make install
```

## But mdb-sql disagrees

```
mdb-sql x.mdb 
You must configure using --enable-sql to get SQL support
```

## Notes

- `--enable-sql` was added to the brew formula by @chenrui333 and @fxcoudert in https://github.com/Homebrew/homebrew-core/commit/341e0d7d9f865dfd6015c17ca9d1baeeab8a2f32
- I do not know if this is an issue with brew, or with `./configure`
- I thought it would be most helpful to raise the issue here (instead of eg. the brew repo) but please let me know if there is a better place 

## Diagnostics

```plain
which mdb-sql
/usr/local/bin/mdb-sql
file /usr/local/bin/mdb-sql
/usr/local/bin/mdb-sql: Mach-O 64-bit executable x86_64
ls -l /usr/local/bin/mdb-sql
lrwxr-xr-x  1 jared  admin  36 Mar 23 14:37 /usr/local/bin/mdb-sql -> ../Cellar/mdbtools/0.9.2/bin/mdb-sql
brew info mdbtools
mdbtools: stable 0.9.2 (bottled)
...
/usr/local/Cellar/mdbtools/0.9.2 (53 files, 991.5KB) *
  Built from source on 2021-03-23 at 14:36:55
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/mdbtools.rb
```

**Comment by evanmiller** [comment]
Thanks for the report.

`--enable-sql` is obsolete, and currently produces the warning

```
$ ./configure --enable-sql
configure: WARNING: unrecognized options: --enable-sql
```

SQL functions are enabled only if copies of Flex and Bison 3.0+ are found at compile-time. I'll modify the `mdb-sql` warning, but I suggest updating the Homebrew formula to require these two programs when compiling.

**Comment by hastebrot** [comment]
For some reason `configure` ignores installed `flex` and `bison`.

```
$ flex --version
flex 2.5.35 Apple(flex-32)

$ bison --version
bison (GNU Bison) 2.3
Written by Robert Corbett and Richard Stallman.
```

```
$  ./configure --enable-man
$ make
$ ./src/util/mdb-sql
You must configure using --enable-sql to get SQL support
```

Output of `configure:`

```
configure:
configure: MDB Tools 0.9.3-beta2 - Configuration summary
configure:
configure:    SQL             : disabled
configure:    ODBC            : disabled
configure:    GLib            : enabled
configure:    man pages       : enabled
configure:    bash-completion : enabled
configure:
```

**Comment by evanmiller** [comment]
@hastebrot Bison 3.0 or later is required; a message to that effect should appear in the configure log.

**Comment by pedromorgan** [comment]
Re #295, my recent experience was the sql was disabled because lexer was not there.. Is there a way to warn ??

**Comment by evanmiller** [comment]
Fixed downstream
