### ISSUE TITLE
mdb-sql: Syntax error when paths contain dashes

### ISSUE THREAD

**Issue by Bob620** [mdbtools/mdbtools#275]
I am using mdb-sql to access various different mdb files with many different uris. I am not able to copy, link, or symlink these to another directory to open in mdb-sql with the current `connect to` functionality.

Example: `/home/user/test-folder/test.mdb`

The valid mdb is located in a valid directory (all valid uri subsets); however, returns the error:
```
File not found
File not found
Unable to locate database /home/user/test
Error at Line : syntax error near -
syntax error near -

Got no result for 'connect to /home/user/test-folder/test.mdb
' command
```

Alternatively, I have been able to connect to the exact same database using the command line:
```
mdb-sql home/user/test-folder/test.mdb
```

While this second method works, it is not as easy for me to implement automatic functionality with and shows that the `connect to` function is not parsing valid uris correctly.

**Comment by evanmiller** [comment]
Please try the proposed fix in #280

**Comment by Bob620** [comment]
It does not seem to work. after compiling and running the branch and doing some testing I was consistently running into
```
1 => connect to /home/chitose/test.MDB
2 => go

Got no result for 'connect to /home/chitose/test.MDB
' command
```

I also tried several different directories and files and got different errors
```
1 => connect to /mnt/c/Users/brude/dev/thermo-reimager/test/data/pfe-mdb/2019-08-12.MDB
2 => go
File not found
File not found
Unable to locate database /mnt/c/Users/brude/dev/thermo-reimager/test/data/pfe-mdb/2019-08-12.MDB
```

```
1 => connect to /home/chitose/test-test/test.mdb
2 => go

Got no result for 'connect to /home/chitose/test-test/test.mdb
' command
```

**Comment by evanmiller** [comment]
@Bob620 Do select statements work in spite of the "Got no result" message?

**Comment by Bob620** [comment]
Seems like it can't finish parsing the command if there are multiple lines, but otherwise yes it is able to.
```
1 => connect to /home/chitose/test.MDB
2 => SELECT * FROM Line
3 => go

Error at Line : syntax error, unexpected SELECT, expecting $end
syntax error, unexpected SELECT, expecting $end

Got no result for 'connect to /home/chitose/test.MDB
SELECT * FROM Line
' command
1 => connect to /home/chitose/test.MDB
2 => go

Got no result for 'connect to /home/chitose/test.MDB
' command
1 => SELECT * FROM Line
2 => go
...
199 Rows retrieved
```

**Comment by evanmiller** [comment]
@Bob620 `go` and `;` are the allowed command separators. Do paths with dashes work now?

(Feel free to open another issue about how 'Got no result' is a confusing message...)

**Comment by Bob620** [comment]
Ok, so that clears up my misunderstanding, I thought newline was a command separator and `go` or `;` would simply execute the commands.

After some testing, the second "File not found" error was my own fault as I misspelled, sorry. so yes, it does fix paths with dashes.

Thank you for the clarification and fix!
