### ISSUE TITLE
configure: WARNING: unrecognized options: --enable-sql

### ISSUE THREAD

**Issue by hastebrot** [mdbtools/mdbtools#295]
Version: 0.9.3-beta2
Source: https://github.com/mdbtools/mdbtools/commit/a47224bb8091bc749a0c583a443b238f42fc5c78
OS: macOS Big Sur

When building from source `configure` ignores `--enable-sql`.

```
$ autoreconf -fvi
$ ./configure --enable-sql --enable-man
```

Output (excerpt):

```
configure: WARNING: unrecognized options: --enable-sql
configure:
configure: MDB Tools 0.9.3-beta2 - Configuration summary
configure:
configure:    SQL             : disabled
configure:    ODBC            : disabled
configure:    GLib            : enabled
configure:    man pages       : enabled
configure:    bash-completion : enabled
```

**Comment by hastebrot** [comment]
This was already reported in #273. 😸 

Closing.

**Comment by pedromorgan** [comment]
On mobile on a train.. but had this recent..
- you need to install lexer headers to make sql work..
- and odbc header files

There should be a warning re lexer
