### ISSUE TITLE
RFE: Allow installing libmdbodbc[W].so outside of the main library path

### ISSUE THREAD

**Issue by jwrdegoede** [mdbtools/mdbtools#315]
I'm working on updating the Fedora packages to mdbtools-0.9.z (thank you for reviving the project), while doing this I ran rpmlint on the generated rpms and it gave these warnings:

mdbtools-devel.x86_64: E: invalid-soname /usr/lib64/libmdbodbc.so libmdbodbc.so
mdbtools-devel.x86_64: E: invalid-soname /usr/lib64/libmdbodbcW.so libmdbodbcW.so

I plan to fix this by moving these 2 files to /usr/lib64/unixODBC where the other ODBC drivers live under Fedora (and putting them in a separate sub-package).

Since these are not real libraries, but rather "drivers" which are intended to be dlopen-ed, it would be nice if an alternate install path like /usr/lib64/unixODBC could be passed to ./configure and then make install would directly place them there rather then in the main library path where they don't really belong.

**Comment by nirgal** [comment]
I have a similar problem on Debian. Here's the patch I'm using.
[01_use_lib_odbc_dir.txt](https://github.com/mdbtools/mdbtools/files/6792904/01_use_lib_odbc_dir.txt)

**Comment by jwrdegoede** [comment]
> I have a similar problem on Debian. Here's the patch I'm using.
> [01_use_lib_odbc_dir.txt](https://github.com/mdbtools/mdbtools/files/6792904/01_use_lib_odbc_dir.txt)

Interesting, this would work for me too. I've a slight preference for using @libdir@/unixODBC though, since that is where the Fedora unixODBC package install the ODBC drivers which come bundled with unixODBC.  But in the end the user needs to put a path to the driver in the used .ini file anyways.

Since you are already using @libdir@/odbc I'll just go with that for Fedora too for consistency.

Any chance the linked patch can be accepted upstream ?

**Comment by evanmiller** [comment]
Happy to merge in a pull request

**Comment by jwrdegoede** [comment]
@evanmiller I see that you've just added this,thanks. I guess that means that this can be closed now ?

**Comment by evanmiller** [comment]
I have added indeed added @nirgal's patch to `dev` (slated for 1.0). If you're happy with the result we can close the issue. If you have a better idea then we can continue the discussion.

**Comment by jwrdegoede** [comment]
I'm happy with the result, so lets close this.
