### ISSUE TITLE
mdbtools public headers (mdbtools.h, mdbsql.h) should not have #ifdef HAVE_FOO in them

### ISSUE THREAD

**Issue by jwrdegoede** [mdbtools/mdbtools#316]
mdbtools public headers (mdbtools.h, mdbsql.h) should not have #ifdef HAVE_FOO in them, there is no guarantee that the same HAVE_FOO defines used when building will also be set when building external projects using libmdb as a dependency.

I've "solved" this with this with the following quick-n-dirty downstream patch in the Fedora packages:

```
Don't use ifdef HAVE_FOO check in the public mdbtools headers.
Note this is a bit of a hack hardcoding the values (HAVE_GLIB && HAVE_ICONV)
used when building the Fedora packages.

This fixes the following compile error when building libgda-mdb:

cc ... -c gda-mdb-provider.c  -fPIC -DPIC -o .libs/gda-mdb-provider.o
In file included from gda-mdb.h:33,
                 from gda-mdb-provider.c:37:
/usr/include/mdbtools.h:38:10: fatal error: mdbfakeglib.h: No such file or directory
   38 | #include <mdbfakeglib.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

diff -up mdbtools-0.9.3/include/mdbsql.h~ mdbtools-0.9.3/include/mdbsql.h
--- mdbtools-0.9.3/include/mdbsql.h~	2020-12-17 20:07:00.000000000 +0100
+++ mdbtools-0.9.3/include/mdbsql.h	2021-07-10 13:02:45.392122848 +0200
@@ -25,11 +25,7 @@
 
 #include <stdio.h>
 #include <string.h>
-#ifdef HAVE_GLIB
 #include <glib.h>
-#else
-#include <mdbfakeglib.h>
-#endif
 #include <mdbtools.h>
 
 typedef struct MdbSQL
diff -up mdbtools-0.9.3/include/mdbtools.h~ mdbtools-0.9.3/include/mdbtools.h
--- mdbtools-0.9.3/include/mdbtools.h~	2021-04-05 15:45:40.000000000 +0200
+++ mdbtools-0.9.3/include/mdbtools.h	2021-07-10 13:02:57.377174793 +0200
@@ -32,17 +32,9 @@
 #include <string.h>
 #include <locale.h>
 
-#ifdef HAVE_GLIB
 #include <glib.h>
-#else
-#include <mdbfakeglib.h>
-#endif
 
-#if defined(HAVE_ICONV)
 #include <iconv.h>
-#elif defined(HAVE_XLOCALE_H)
-#include <xlocale.h>
-#endif
 
 #ifdef _WIN32
 #include <io.h>
```

A better solution would probably to have .in files for the public headers and have autoconf generate headers without the ifdef-s based on the setting used when building.

@nirgal I'm a bit surprised that you did not see this issue in Debian ?

**Comment by jwrdegoede** [comment]
I see that Debian does not build the mdb-provider of libgda, that is likely why Debian is not seeing the build-error caused by this.

I've submitted a merge-req to libgda upstream to make the mdb-provider build against mdbtools-0.9.z:
https://gitlab.gnome.org/GNOME/libgda/-/merge_requests/178

**Comment by evanmiller** [comment]
@jwrdegoede Thanks for the report. I agree with the `.in` solution you proposed.

**Comment by jwrdegoede** [comment]
> OK, after struggling with various platform issues I have come up with an `.in` solution. Try the latest `dev` commits.

Thank you for doing this. I'm afraid I don't have time to test. I do have taken a quick look at the commit making the change and that looks good to me.

**Comment by evanmiller** [comment]
OK. This is slated for 1.0 since it's a significant breaking change. I don't have a particular timeline for a release - just wanted to start collecting major breaking changes all in one place :-)

**Comment by jwrdegoede** [comment]
I understand, but this should not break anything, should it ?

Will 1.0 again bump the soname (I hope not) ?

**Comment by evanmiller** [comment]
This breaks the `MdbHandle` structure. I'll need to think about the client-side implications. E.g. `sizeof(MdbHandle)` will change for some users.

**Comment by evanmiller** [comment]
Interesting. Seems like a good idea. Anyways I am not in a rush for 1.0 so we should have plenty of time to work something out.

**Comment by evanmiller** [comment]
`MdbBackend` also has new fields, introduced in #321 and #322. GMDB2 does use the `capabilities` field of that structure. It's not all that useful outside of libmdb, but it's possible there are other clients. Might want to move the new fields to the end to preserve ABI.

**Comment by jwrdegoede** [comment]
is the MdbBackend struct always allocated by libmdb itself? If yes then it should be safe to add fields to the end without breaking the ABI, but if it may get allocated by API users then adding fields means we will need a soname bump.

Note a soname bump is not the end of the world, there are not that many packages which depend on libmdb and then will also need a rebuild. So if a soname build is necessary then that is fine too.

**Comment by evanmiller** [comment]
It's allocated by `mdb_register_backend`, which has some new arguments (so maybe another ABI break?). This can be worked around by adding a new function, I guess.

The larger problem with MDB Tools is that there is virtually no distinction between the public and private APIs. In an ideal world mdb_register_backend would be private. If we're doing a soname bump, then I'd want to privatize as much as possible so we don't have to go through this with every new feature.

**Comment by evanmiller** [comment]
I've followed your suggestions and restored the old struct layouts and APIs as much as possible. `MdbBackend` has new fields at the end, but clients should have been using the API to allocate it, so there shouldn't be any breakage.

The planned libtool number for version 1.0 is now `4:0:1`. For version 0.9.4 it was `3:4:0`. I'm not well-versed in these things but I believe that the soname will not change.

If the 1.0 Beta 3 looks OK to you, feel free to close this issue.

**Comment by jwrdegoede** [comment]
> I've followed your suggestions and restored the old struct layouts and APIs as much as possible. `MdbBackend` has new fields at the end, but clients should have been using the API to allocate it, so there shouldn't be any breakage.
> 
> The planned libtool number for version 1.0 is now `4:0:1`. For version 0.9.4 it was `3:4:0`. I'm not well-versed in these things but I believe that the soname will not change.
> 
> If the 1.0 Beta 3 looks OK to you, feel free to close this issue.

I've just done a quick test-build of 1.0.0-beta4 for Fedora and both the headers as well as the soname look good to me, thank you. Closing.
