### ISSUE TITLE
SELECT COUNT(*) broken in 0.9.3

### ISSUE THREAD

**Issue by rouault** [mdbtools/mdbtools#318]
In 0.9.3, SELECT COUNT(*) is broken, whereas working in previous versions

```
$ echo "select COUNT(*) from polys" | ~/mdbtools/src/util/mdb-sql ../autotest/ogr/data/pgeo/sample.mdb
Error at Line : syntax error, unexpected PATH, expecting IDENT or NAME or COUNT or '*'
syntax error, unexpected PATH, expecting IDENT or NAME or COUNT or '*'

Got no result for 'select COUNT(*) from polys
' command
```

git bisect points https://github.com/mdbtools/mdbtools/commit/d05c86fa3dbe46d86dd942873ab4099a81fe6088 as the culprit commit

**Comment by Bob620** [comment]
I see the problem, Ill take a look later today and report back.

**Comment by Bob620** [comment]
@rouault or @prusswan, can you try eff5934?

**Comment by rouault** [comment]
> @rouault or @prusswan, can you try [eff5934](https://github.com/mdbtools/mdbtools/commit/eff5934702711dccf76d341124e589bd1c716565)?

That doesn't work

**Comment by Bob620** [comment]
> 
> 
> > @rouault or @prusswan, can you try [eff5934](https://github.com/mdbtools/mdbtools/commit/eff5934702711dccf76d341124e589bd1c716565)?
> 
> That doesn't work

Try f7662e1

**Comment by rouault** [comment]
> Try [f7662e1](https://github.com/mdbtools/mdbtools/commit/f7662e18ea07694f97e1d1038359af55a01b9987)

works for me

**Comment by Bob620** [comment]
Sweet, Ill need to do some more work to keep ( and ) working in URIs but I know the issues now
