### ISSUE TITLE
GMDB2: Testers needed

### ISSUE THREAD

**Issue by evanmiller** [mdbtools/mdbtools#323]
Hey folks, I spent a few days dusting off @brianb's old GUI program `gmdb2` and porting it to GTK+3. As a result, many obsolete package requirements have been dropped, and the interface has a clean new look. I've packaged up a beta release here:

https://github.com/mdbtools/gmdb2/releases/tag/v0.9.0-beta2

`gmdb2` lets you open, view, and query Access databases in a desktop program instead of using the command line. The program was split off into its own GitHub project many months back, so go ahead and give it a Star if you like what you see.

If everything looks good I will put out an official 0.9.0 release in a few weeks and we can start shopping it around to package managers. Many distros dropped gmdb2 in the past few years due to the outdated run-time requirements, but the new version should run just fine on any modern Linux. Try it out!

**Comment by pedromorgan** [comment]
Looked at gmdb2 a while back; thoughts then were to port to  QT (mainly for cross platform ease)

**Comment by evanmiller** [comment]
@pedromorgan Please try out the latest beta.... A QT port is far outside the current scope of things.

**Comment by pedromorgan** [comment]
## Report

- So clicked everything in sight and failed to make it crash ;-)))), and  on a few big databases
- Most of the issues I would want to file are GUI related, eg default sizes  or sizes etc

**Comment by evanmiller** [comment]
@pedromorgan Thanks for the report!
