### ISSUE TITLE
libmdb.so.4: cannot open shared object file

### ISSUE THREAD

**Issue by pedromorgan** [mdbtools/mdbtools#324]
In response to #312 I decided to "clean checkout" and recompile latest

- on sudo make install results in error below (extracted part)..

however now running `mdb-ver` return error
```mdb-ver: error while loading shared libraries: libmdb.so.4: cannot open shared object file: No such file or directory```

and `which mdb-ver` returns`/usr/local/bin/mdb-ver`

```
make[4]: Entering directory '/home/mdbtools/mdbtools/src/sql'
 /usr/bin/mkdir -p '/usr/local/lib'
 /bin/bash ../../libtool   --mode=install /usr/bin/install -c   libmdbsql.la '/usr/local/lib'
libtool: warning: relinking 'libmdbsql.la'

```

**Comment by evanmiller** [comment]
Please try Beta 3 and see if that fixes things

**Comment by rhurlin** [comment]
Don't know if this happens only for me on FreeBSD: 
Beta 2 produces `libmdb.so.4.0.0` and `libmdbsql.so.4.0.0`, Beta 3 produces `libmdb.so.3.1.0` and `libmdbsql.so.3.1.0` again.

Is this intended?

**Comment by evanmiller** [comment]
@rhurlin Yes, this is expected. See #316

**Comment by rhurlin** [comment]
@evanmiller Thanks for clarification.
