### ISSUE TITLE
mdb-schema: --drop-table / --no-drop-table show/hide 'CREATE TABLE' string

### ISSUE THREAD

**Issue by fawick** [mdbtools/mdbtools#328]
I recently started using mdb-tools (v1.0.0-beta2) to try to extract tables from an existing MDB file. Upon using `mdb-schema` I noticed that the options `--drop-table`/`--no-drop-table` do not alter the `DROP TABLE` statements, but have an effect on whether the `CREATE TABLE` appears in the output.

I found this odd behaviour to be happening for backends `sqlite`, `mysql`, `sybase`, `oracle`, and the default format (`access`). On the other hand, the options seem to behave correctly for the backend `postgres`. 

For example, consider the following table 
![image](https://user-images.githubusercontent.com/1886500/130224167-d22f31b5-2355-4f1e-a996-3e1bfe36f6ec.png)

Here's the output of `mdb-schema`:
```
$ src/util/mdb-schema -T tblStudent legacy.mdb sqlite
-- ----------------------------------------------------------
-- MDB Tools - A library for reading MS Access database files
-- Copyright (C) 2000-2011 Brian Bruns and others.
-- Files in libmdb are licensed under LGPL and the utilities under
-- the GPL, see COPYING.LIB and COPYING files respectively.
-- Check out http://mdbtools.sourceforge.net
-- ----------------------------------------------------------

-- That file uses encoding UTF-8

DROP TABLE IF EXISTS `tblStudent`;
 (
	`IDStudent`			INTEGER,
	`Name`			varchar,
	`Shortname`			varchar,
	`RegistrationDate`			DateTime,
	`RegistrationOADate`			REAL
);
```

The option `--no-drop-table` has no effect:

```
$ src/util/mdb-schema --no-drop-table -T tblStudent legacy.mdb sqlite
-- ----------------------------------------------------------
-- MDB Tools - A library for reading MS Access database files
-- Copyright (C) 2000-2011 Brian Bruns and others.
-- Files in libmdb are licensed under LGPL and the utilities under
-- the GPL, see COPYING.LIB and COPYING files respectively.
-- Check out http://mdbtools.sourceforge.net
-- ----------------------------------------------------------

-- That file uses encoding UTF-8

DROP TABLE IF EXISTS `tblStudent`;
 (
	`IDStudent`			INTEGER,
	`Name`			varchar,
	`Shortname`			varchar,
	`RegistrationDate`			DateTime,
	`RegistrationOADate`			REAL
);
```

The option `--drop-table` caused the `CREATE TABLE` statement to appear:

```
$ src/util/mdb-schema --drop-table -T tblStudent legacy.mdb sqlite
-- ----------------------------------------------------------
-- MDB Tools - A library for reading MS Access database files
-- Copyright (C) 2000-2011 Brian Bruns and others.
-- Files in libmdb are licensed under LGPL and the utilities under
-- the GPL, see COPYING.LIB and COPYING files respectively.
-- Check out http://mdbtools.sourceforge.net
-- ----------------------------------------------------------

-- That file uses encoding UTF-8

CREATE TABLE `tblStudent`
DROP TABLE IF EXISTS `tblStudent`;
 (
	`IDStudent`			INTEGER,
	`Name`			varchar,
	`Shortname`			varchar,
	`RegistrationDate`			DateTime,
	`RegistrationOADate`			REAL
);
```

**Comment by fawick** [comment]
I might have found the cause already. In the function `mdb_register_backend` the order of the parameters seems to be wrong. Here is is in the order `<drop statement>, <create statement>`:

https://github.com/mdbtools/mdbtools/blob/148eed1546efa63f52df42dc5fe0bca65cd99e77/src/libmdb/backend.c#L469-L482

While in the function header of `mdbi_register_backend2` it is `<create statement>, <drop statement>`

https://github.com/mdbtools/mdbtools/blob/148eed1546efa63f52df42dc5fe0bca65cd99e77/src/libmdb/backend.c#L419-L432

The postgres backend calls `mdbi_register_backend2` directly, while all other backends seem to use the bugged wrapper `mdb_register_backend`.

**Comment by evanmiller** [comment]
Hi, does this behavior exist in version 0.9.4? I am currently working through some binary incompatibilities between the 0.9 and 1.0 series. It's possible that your 1.0 tools are linking to the installed 0.9 libmdb library and causing erratic behavior. I mention this because there are specifically issues that affect CREATE TABLE. These issues will be addressed in Beta 3.

**Comment by fawick** [comment]
No, 0.9.4 is not affected by this bug.

**Comment by fawick** [comment]
Neither is v1.0.0-beta1... The problem got introduced with 7fb7660b09a427d5a9ec36f41e257748c8651ebd.

**Comment by evanmiller** [comment]
@fawick I see the bug, will fix

**Comment by fawick** [comment]
Great, thanks!
