### ISSUE TITLE
Remove iconv requirement from libmdbodbcW

### ISSUE THREAD

**Issue by evanmiller** [mdbtools/mdbtools#332]
I am investigating the possibility of removing the iconv requirement from the ODBC wide-char functions. Here are my notes.

libmdbodbcW is a separate driver that includes all of the *W functions. It can only be built with iconv at the moment, but it may be possible to have a `wcstombs` based implementation, similar to the below, that obviates the need for iconv. I believe that this would let us consolidate the two ODBC drivers into one, or at least symlink one from the other for backward compatibility.

Currently, libmdb is able to perform UTF-16LE to UTF-8 string conversions with `wcstombs` when iconv is not available. This lets us handle JET4 and later files without iconv. Endianness and 4-byte `wchar_t` values are handled correctly. The code is here:

https://github.com/mdbtools/mdbtools/blob/00d597b6d35da97661b1b4d87ad59ca9f29908a7/src/libmdb/iconv.c#L91-L118

However, when it comes to ODBC, an issue arises because `SQLWCHAR` may not be the same size as `wchar_t` on all systems, so we can't call `wcstombs` directly. My understanding from this page:

http://manual.freeshell.org/freetds/userguide/uodbc.htm

is that unixODBC defines SQLWCHAR to be 2 bytes always, but iODBC defines it to be the same as `wchar_t`. So there will be some preprocessing necessary, and the libmdb conversion functions can't be used out of the box in the ODBC driver.

I believe that this preprocessing may be as simple as:

```C
wchar_t * convert_sqlwchar_to_wchar_t(SQLWCHAR *string, size_t len) {
    wchar_t *new_string = malloc((len+1) * sizeof(wchar_t));
    for (size_t i=0; i<len; i++) {
        // assign to possibly-wider type of same endianness
        new_string[i] = string[len];
    }
    new_string[len] = '\0';
    return new_string;
}
```

If so then completely removing iconv from the ODBC driver should be achievable in time for the 1.0 release.

**Comment by nirgal** [comment]
iconv is quite usefull to handle JET3 data files. Do you want to drop its support? I'm confused I guess.

**Comment by evanmiller** [comment]
Iconv will remain in the main libmdb library. The purpose is to remove it from the compiled ODBC driver.
