### ISSUE TITLE
Error when running autoreconf -i -f on Ubuntu Server 20.04

### ISSUE THREAD

**Issue by jspinella** [mdbtools/mdbtools#345]
If it's not really an issue feel free to close... 

On a fresh install of Ubuntu 20.04, in order for the autoreconf -i -f to run successfully (I tried 0.9.4 and the latest 1.0.0 beta 4) I needed to install gettext e.g. `sudo apt install gettext` as well as the other dependencies listed in the README.md (e.g. libtool, automake, autoconf). I don't know if this is an Ubuntu-specific issue but it may be worth adding to the README.md so people don't have to go hunting the Internet for a solution.

The error I was getting during the autoreconf that was resolved by installing the gettext package: `error: possibly undefined macro: AC_LIB_PREPARE_PREFIX`

**Comment by evanmiller** [comment]
autoreconf is not necessary when installing from the tarballs. You can start with ./configure.
