### ISSUE TITLE
Incorrect date export

### ISSUE THREAD

**Issue by scherbatey** [mdbtools/mdbtools#346]
In version: 0.9.4
Steps:

1. Export tblApplication table from this DB:
https://ohiodnr.gov/static/documents/oil-gas/rbdms/Rbdmsd9708262021.zip
(Download page: https://ohiodnr.gov/wps/portal/gov/odnr/discover-and-learn/safety-conservation/about-ODNR/oil-gas/oil-gas-resources/featured-content-3):

$ mkdir /tmp/db; cd /tmp/db
$ wget https://ohiodnr.gov/static/documents/oil-gas/rbdms/Rbdmsd9708262021.zip
$ unzip Rbdmsd9708262021.zip
$ mdb-export -I sqlite -S 1 /tmp/db/Rbdmsd97.mdb tblStimulation | grep \\\\-2038986005 

INSERT INTO `tblStimulation` (`STIMULATIONID`, `API_WELLNO`, `DT_TREAT`, `TOP`, `BOT`, `ST_FMTN_CD`, `TOP_FM`, `BOT_FM`, `STIM_HOLE`, `OH_TOP`, `OH_BASE`, `FRAC_ACID`, `UNITS`, `VOL`, `LBS_PROP`, `ACID_CON`, `MBPRESS`, `MTPRESS`, `MISIP`, `_5SIP`, `BHP`, `CMMNT`, `DT_MOD`, `UPSIZE_TS`, `FRAC_WIT`, `BOP_TYPE`, `BOP_WIT`, `PRESS_RATE_GRAPH`, `RECORD`, `INVOICE`, `FRAC_DATE`, `AVG_RATE`, `FRAC_CO`, `CIRCULATION`, `VALVESCLOSED`, `OKtoTransfer`, `INSPECTOR`) VALUES (-2038986005,"34111247920000","2018-08-01 00:00:00",22930,23090,"364005",0,0,"CS",0,0,"H2O","Gal",324897,441160,15,10123,10382,6732,6204,0,"STAGE 1 OF 54","2019-03-13 **14:43:32**",NULL,0,NULL,0,1,1,1,NULL,73.89994049072266,26005,NULL,NULL,0,NULL);

2. Compare with the same records in MS Access:
SELECT DT_MOD FROM tblStimulation WHERE STIMULATIONID = -2038986005
DT_MOD
3/13/2019 **3:28:32** PM

**Comment by scherbatey** [comment]
I found that bug is introduced by [**this change**](https://github.com/mdbtools/mdbtools/commit/fe77bc5c8e9eed86c93b26d43d89e1b83d3f889c#diff-ec43fb6d4838106eacbf71c0b8ac6c1e89ef30713444db8691d0857f28fc49f1) 

However, [this one](dccc88b7) fixes the issue somehow in this particular case

**Comment by evanmiller** [comment]
Thanks for the report. Dates are stored as double-precision, so the linked commit has fixed the issue in dev.
