### ISSUE TITLE
Using odbc driver in c# .net 3.1 gives encoding with chinese signs

### ISSUE THREAD

**Issue by ShinAkuma-** [mdbtools/mdbtools#347]
- OS Ubuntu 20.04
- unixODBC 2.3.6, but had similar results on other versions
- mdbtools-1.0.0-beta4 , compiled with and without iconv

**/etc/odbc.ini**
[test]
Description=test
Driver=MDBW
ServerName = localhost
Database=/home/micke/test.mdb

**/etc/odbcinst.ini**
[MDBW]
Description=MDBTools Driver Wide
Driver=/usr/local/lib/odbc/libmdbodbcW.so
Setup=/usr/local/lib/odbc/libmdbodbcW.so
FileUsage=1
UsageCount=1
[ODBC]
Trace=1
TraceFile=/tmp/mdb.log

When using isql to query the odbc driver works fine
isql test
SQL> SELECT Text FROM ValueText limit 10
+-----------------------------------------------------------------------------------------------------+
| Text                                                                                                |
+-----------------------------------------------------------------------------------------------------+
| mm                                                                                                  |
| cm                                                                                                  |
| Level 2                                                                                             |
| Line stacking 1345                                                                                  |
| Line stacking 1346                                                                                  |
| Line stacking 1347                                                                                  |
| Line stacking 1348                                                                                  |
| Line stacking 1349                                                                                  |
| Line stacking 1350                                                                                  |
| Line stacking 1351                                                                                  |
+-----------------------------------------------------------------------------------------------------+
SQLRowCount returns 10
10 rows fetched

But when running the same query from c# in a .net core 3.1 app the results seem to have bad encoding (nuget package System.Data.Odbc 6.0.0-preview.7.21377.19)
``` c#
using System;
using System.Data.Odbc;

namespace odbc_test
{
    class Program
    {
        static void Main(string[] args)
        {
            string connetionString = "DSN=test;";
            OdbcConnection cnn = new OdbcConnection(connetionString);
            cnn.Open();
            OdbcCommand DbCommand = cnn.CreateCommand();
            DbCommand.CommandText = "SELECT Text FROM ValueText limit 10";
            OdbcDataReader DbReader = DbCommand.ExecuteReader();
            while (DbReader.Read())
            {
                Console.WriteLine(DbReader.GetString(0));
            }
        }
    }
}
```
浭
浣
敌敶⁬
楌敮猠慴正湩⁧㌱㔴
楌敮猠慴正湩⁧㌱㘴
楌敮猠慴正湩⁧㌱㜴
楌敮猠慴正湩⁧㌱㠴
楌敮猠慴正湩⁧㌱㤴
楌敮猠慴正湩⁧㌱〵
楌敮猠慴正湩⁧㌱ㄵ

Logs are attached.
maybe of note. 
isql UNICODE Using encoding ASCII 'UTF-8' and UNICODE 'UCS-2LE'
c#   UNICODE Using encoding ASCII 'ANSI_X3.4-1968' and UNICODE 'UCS-2LE'

[mdb_isql.log](https://github.com/mdbtools/mdbtools/files/7079858/mdb_isql.log)
[mdb_csharp.log](https://github.com/mdbtools/mdbtools/files/7079859/mdb_csharp.log)

**Comment by evanmiller** [comment]
Hi, thanks for the report. Do you see the same issue with 1.0.0-beta3?

**Comment by ShinAkuma-** [comment]
Hello,
Yes I seem to get the same problem with beta3 and 0.9.4. I'll attach logs for all variants.

[mdb_isql_0.9.4.log](https://github.com/mdbtools/mdbtools/files/7081795/mdb_isql_0.9.4.log)
[mdb_csharp_0.9.4.log](https://github.com/mdbtools/mdbtools/files/7081796/mdb_csharp_0.9.4.log)
[mdb_isql_beta3.log](https://github.com/mdbtools/mdbtools/files/7081797/mdb_isql_beta3.log)
[mdb_csharp_beta3.log](https://github.com/mdbtools/mdbtools/files/7081798/mdb_csharp_beta3.log)

**Comment by evanmiller** [comment]
Thanks for checking – just wanted to make sure it wasn't an issue with #333.

Can you try the non-Wide driver? /usr/local/lib/odbc/libmdbodbc.so

**Comment by ShinAkuma-** [comment]
I get the same with the non-wide driver, tested 0.9.4 and beta 4 no inconv and with.

Some extra info:
```
micke@micke-VirtualBox:~/repos/mdbtools-0.9.4$ mdb-ver ~/test.mdb 
JET4
micke@micke-VirtualBox:~/repos/mdbtools-0.9.4$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=sv_SE.UTF-8
LC_TIME=sv_SE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=sv_SE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=sv_SE.UTF-8
LC_NAME=sv_SE.UTF-8
LC_ADDRESS=sv_SE.UTF-8
LC_TELEPHONE=sv_SE.UTF-8
LC_MEASUREMENT=sv_SE.UTF-8
LC_IDENTIFICATION=sv_SE.UTF-8
LC_ALL=
```

I'll test some other ODBC driver like MySQL later to see that it is not unixODBC or maybe the C# odbc that is causing the problem.

[mdb_isql_0.9.4_notw.log](https://github.com/mdbtools/mdbtools/files/7084999/mdb_isql_0.9.4_notw.log)
[mdb_csharp_0.9.4_notw.log](https://github.com/mdbtools/mdbtools/files/7085000/mdb_csharp_0.9.4_notw.log)
[mdb_csharp_beta4_noiconv_notw.log](https://github.com/mdbtools/mdbtools/files/7085001/mdb_csharp_beta4_noiconv_notw.log)
[mdb_csharp_beta4_notw.log](https://github.com/mdbtools/mdbtools/files/7085002/mdb_csharp_beta4_notw.log)
[mdb_isql_beta4_notw.log](https://github.com/mdbtools/mdbtools/files/7085003/mdb_isql_beta4_notw.log)
[mdb_isql_beta4_noiconv_notw.log](https://github.com/mdbtools/mdbtools/files/7085004/mdb_isql_beta4_noiconv_notw.log)

**Comment by evanmiller** [comment]
I think I "sort of" see what's going on...

The ideograph 楌 in Row 4 is UTF-16LE encoded as

0x4C  0x69

(See https://unicode-table.com/en/694C/)

In ASCII those codes are "L" and "i", e.g. the beginning of "Line stacking XXXX". So it looks like the C# driver is expecting UTF-16LE output but the ODBC driver is providing UTF-8 output.

The "Wide" library is intended to solve this problem but it includes only a limited number of functions – so maybe C# is falling back to the non-Wide functions (which are also included in the Wide library).

**Comment by evanmiller** [comment]
Please try the Wide driver in #348.

**Comment by aminabbasi604** [comment]
i have same bug

**Comment by ShinAkuma-** [comment]
Hello, Sorry for the late reply I have been swamped with work.
Here are some logs for the 348 build.

micke@micke-VirtualBox:~/repos/mdbtools$ git log
commit 232c988e813a28de1326a24c7982ed4280710886 (HEAD -> sqlfetchw, origin/sqlfetchw)
Author: Evan Miller <emmiller@gmail.com>
Date:   Tue Aug 31 14:23:12 2021 -0400

Implement SQLFetchW
    
Fixes #347

I still get the same bytes, if i decode as the first entry that is 'mm' in the database as unicode (UTF16LE) i get the bytes 0x6D 0x6D that gives https://unicode-table.com/en/6D6D/ i think the expected result would be 0x6D 0x00 0x6D 0x00.

And if I decode, as UTF-8 I get 0xE6 0xB5 0xAD the corresponding utf-8 of  https://unicode-table.com/en/6D6D/

I'll get a more thorough, follow up tomorrow. I'm in Europe so maybe sometime around 10:00 CET.

[mdb_csharp_348.log](https://github.com/mdbtools/mdbtools/files/7117730/mdb_csharp_348.log)
[mdb_isql_348.log](https://github.com/mdbtools/mdbtools/files/7117732/mdb_isql_348.log)

**Comment by evanmiller** [comment]
Hmm - the log indicates that `SQLFetch` is still being called (with a return type of `SQL_WCHAR`) rather than `SQLFetchW`. This is surprising but maybe the correct solution is to support the WCHAR return type. Please double-check to ensure that the latest driver (now part of 1.0.0-beta5) is being installed and tested.

**Comment by ShinAkuma-** [comment]
Here is a printout from the test program where there is a print of the bytes first. then default encoding for the program and utf16le.

UTF16 Bytes: 6D6D
UTF8 Bytes: E6B5AD
Default encoding: 浭
Forced Unicode encoding: mm
UTF16 Bytes: 636D
UTF8 Bytes: E6B5A3
Default encoding: 浣
Forced Unicode encoding: cm
UTF16 Bytes: 4C6576656C20
UTF8 Bytes: E6958CE695B6E281AC
Default encoding: 敌敶⁬
Forced Unicode encoding: Level 
UTF16 Bytes: 4C696E6520737461636B696E672031333435
UTF8 Bytes: E6A58CE695AEE78CA0E685B4E6ADA3E6B9A9E281A7E38CB1E394B4
Default encoding: 楌敮猠慴正湩⁧㌱㔴
Forced Unicode encoding: Line stacking 1345
UTF16 Bytes: 4C696E6520737461636B696E672031333436
UTF8 Bytes: E6A58CE695AEE78CA0E685B4E6ADA3E6B9A9E281A7E38CB1E398B4
Default encoding: 楌敮猠慴正湩⁧㌱㘴
Forced Unicode encoding: Line stacking 1346
UTF16 Bytes: 4C696E6520737461636B696E672031333437
UTF8 Bytes: E6A58CE695AEE78CA0E685B4E6ADA3E6B9A9E281A7E38CB1E39CB4
Default encoding: 楌敮猠慴正湩⁧㌱㜴
Forced Unicode encoding: Line stacking 1347
UTF16 Bytes: 4C696E6520737461636B696E672031333438
UTF8 Bytes: E6A58CE695AEE78CA0E685B4E6ADA3E6B9A9E281A7E38CB1E3A0B4
Default encoding: 楌敮猠慴正湩⁧㌱㠴
Forced Unicode encoding: Line stacking 1348
UTF16 Bytes: 4C696E6520737461636B696E672031333439
UTF8 Bytes: E6A58CE695AEE78CA0E685B4E6ADA3E6B9A9E281A7E38CB1E3A4B4
Default encoding: 楌敮猠慴正湩⁧㌱㤴
Forced Unicode encoding: Line stacking 1349
UTF16 Bytes: 4C696E6520737461636B696E672031333530
UTF8 Bytes: E6A58CE695AEE78CA0E685B4E6ADA3E6B9A9E281A7E38CB1E380B5
Default encoding: 楌敮猠慴正湩⁧㌱〵
Forced Unicode encoding: Line stacking 1350
UTF16 Bytes: 4C696E6520737461636B696E672031333531
UTF8 Bytes: E6A58CE695AEE78CA0E685B4E6ADA3E6B9A9E281A7E38CB1E384B5
Default encoding: 楌敮猠慴正湩⁧㌱ㄵ
Forced Unicode encoding: Line stacking 1351

The lines with Unicode is almost right but some lines ends up short, probably due to encoding issues creating linebreaks or something.

For example.
UTF16 Bytes: 4C6576656C20
UTF8 Bytes: E6958CE695B6E281AC
Default encoding: 敌敶⁬
Forced Unicode encoding: Level 

Should be Level 2

Logs from beta5 attached

configure: MDB Tools 1.0.0-beta5 - Configuration summary
configure: 
configure:    SQL             : enabled
configure:    ODBC            : enabled
configure:    GLib            : disabled
configure:    iconv           : enabled
configure:    man pages       : enabled
configure:    bash-completion : enabled

[mdb_isql_beta5.log](https://github.com/mdbtools/mdbtools/files/7120251/mdb_isql_beta5.log)
[mdb_csharp_beta5.log](https://github.com/mdbtools/mdbtools/files/7120252/mdb_csharp_beta5.log)

**Comment by evanmiller** [comment]
Thanks for the update. Please try the code in #349.

**Comment by ShinAkuma-** [comment]
In 349 we get new bytes that seems like the expected encoding, but the strings seems to get cut a bit short. I haven't really manually checked all the raw bytes compared to the resulting strings yet but i might do that tomorrow if i have the time. 

Here is the print out
UTF16 Bytes: 6D00
UTF8 Bytes: 6D
Default encoding: m
Forced Unicode encoding: m
UTF16 Bytes: 6300
UTF8 Bytes: 63
Default encoding: c
Forced Unicode encoding: c
UTF16 Bytes: 4C0065007600
UTF8 Bytes: 4C6576
Default encoding: Lev
Forced Unicode encoding: Lev
UTF16 Bytes: 4C0069006E00650020007300740061006300
UTF8 Bytes: 4C696E652073746163
Default encoding: Line stac
Forced Unicode encoding: Line stac
UTF16 Bytes: 4C0069006E00650020007300740061006300
UTF8 Bytes: 4C696E652073746163
Default encoding: Line stac
Forced Unicode encoding: Line stac
UTF16 Bytes: 4C0069006E00650020007300740061006300
UTF8 Bytes: 4C696E652073746163
Default encoding: Line stac
Forced Unicode encoding: Line stac
UTF16 Bytes: 4C0069006E00650020007300740061006300
UTF8 Bytes: 4C696E652073746163
Default encoding: Line stac
Forced Unicode encoding: Line stac
UTF16 Bytes: 4C0069006E00650020007300740061006300
UTF8 Bytes: 4C696E652073746163
Default encoding: Line stac
Forced Unicode encoding: Line stac
UTF16 Bytes: 4C0069006E00650020007300740061006300
UTF8 Bytes: 4C696E652073746163
Default encoding: Line stac
Forced Unicode encoding: Line stac
UTF16 Bytes: 4C0069006E00650020007300740061006300
UTF8 Bytes: 4C696E652073746163
Default encoding: Line stac
Forced Unicode encoding: Line stac

So for example. Lev seems to clearly have a longer array of bytes than the L e v that is printed
Default encoding: Lev
Forced Unicode encoding: Lev
UTF16 Bytes: 4C0069006E00650020007300740061006300
UTF8 Bytes: 4C696E652073746163



[mdb_isql_349.log](https://github.com/mdbtools/mdbtools/files/7123655/mdb_isql_349.log)
[mdb_csharp_349.log](https://github.com/mdbtools/mdbtools/files/7123656/mdb_csharp_349.log)

**Comment by evanmiller** [comment]
Thanks. I've force-pushed a change to address the truncation issue.

**Comment by ShinAkuma-** [comment]
This seems to work well. I have only ran a quick test but it looks good!


[mdb_csharp_349_force_d7e14c8.log](https://github.com/mdbtools/mdbtools/files/7127669/mdb_csharp_349_force_d7e14c8.log)

**Comment by evanmiller** [comment]
@ShinAkuma- Sounds good! In the process I was able to get rid of some code that was never actually called.
