### ISSUE TITLE
A very serious issue when exporting tables including numbers with mdb-export

### ISSUE THREAD

**Issue by Hoss3770** [mdbtools/mdbtools#350]
Numbers larger than 127 are turned negative (regression):

[11100.mdb.zip](https://github.com/mdbtools/mdbtools/files/7219151/11100.mdb.zip)
[test.csv.zip](https://github.com/mdbtools/mdbtools/files/7219178/test.csv.zip)

`mdb-export 11100.mdb t11100 > test.csv`

Near the end of the CSV file -127 is present instead of 130. Reproduced on latest master and dev. 
v0.9.0-beta1 is correct however.

**Comment by evanmiller** [comment]
Thanks for the report. I am able to reproduce the issue, introduced in v0.9.3-beta1. It will be fixed in the 1.0 release.
