### ISSUE TITLE
Error with Make - g_memdup

### ISSUE THREAD

**Issue by joofio** [mdbtools/mdbtools#356]
Hi,

I am with MacOS monterey M1 and configure goes smooth but then it make, it returns error regarding g_memdup
"file.c:303:25: error: 'g_memdup' is deprecated: Use 'g_memdup2' instead [-Werror,-Wdeprecated-declarations]
        newmdb = (MdbHandle *) g_memdup2(mdb, sizeof(MdbHandle));
"

"file.c:310:10: error: 'g_memdup' is deprecated: Use 'g_memdup2' instead [-Werror,-Wdeprecated-declarations]
                data = g_memdup2(entry,sizeof(MdbCatalogEntry));
"

can you help me with this? 
Thanks

**Comment by evanmiller** [comment]
This should be fixed in `dev`.
