### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by nirgal** [mdbtools/mdbtools#358]
Hello

The new file api_docx/custom.css.map contains binary data.

Thus the version 1.0 of mdbtools cannot be distributed as is on Debian and relatives.

Can this file be removed from the source, or generated somehow?

**Comment by pedromorgan** [comment]
That's a map file generated by the sass compiler and its json, not binary.

Can be nuked as its not essential.

**Comment by nirgal** [comment]
Not real binary, that's true. But it is a generated file nonetheless, with a lot of hexadecimal data in it, and thus cannot be distributed in the source, as per Debian standards.

How can it be generated?
Can you add the build dependencies and alter the makefile?

**Comment by pedromorgan** [comment]
Had a quick look (am travelling)
- are you distributing the "api_docx/" directory. this only contains the "sources" for the doxygen docs
- I can't see the apidocs being built in makefile
- does is even need including in the dist ?

I'll make a PR later today to get rid of the file ;-))

**Comment by nirgal** [comment]
I am not distributing the api_docx in the binary package.

However, it's in the source tarball, and this is forbidden for me to release generated files in a "source". And no source means no binary, here.
I temporarily hacked the source, removing that file, and released a version 1.0.0+dsfg (stands for debian free software guidelines).
I worked it around. But I believe it is safer to stick to the rule that the sources should not contain generated files, especially when it has hexadecimal raw data that can't be explained, for everyone's sake and safety.
