### ISSUE TITLE
install mdbtools on centos 8

### ISSUE THREAD

**Issue by MrNico** [mdbtools/mdbtools#362]
Hello, I need to install mdbtools on a centos 8, I am following what is indicated here, but I have the following error

configure.ac:99: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
m4/iconv.m4:16: AM_ICONV_LINKFLAGS_BODY is expanded from...
m4/iconv.m4:27: AM_ICONV_LINK is expanded from...
m4/iconv.m4:243: AM_ICONV is expanded from...
configure.ac:99: the top level
configure.ac:99: warning: AC_LIB_RPATH is m4_require'd but not m4_defun'd
m4/iconv.m4:16: AM_ICONV_LINKFLAGS_BODY is expanded from...
m4/iconv.m4:27: AM_ICONV_LINK is expanded from...
m4/iconv.m4:243: AM_ICONV is expanded from...
configure.ac:99: the top level
configure.ac:99: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
m4/iconv.m4:16: AM_ICONV_LINKFLAGS_BODY is expanded from...
m4/iconv.m4:27: AM_ICONV_LINK is expanded from...
m4/iconv.m4:243: AM_ICONV is expanded from...
configure.ac:99: the top level
configure.ac:99: warning: AC_LIB_RPATH is m4_require'd but not m4_defun'd
m4/iconv.m4:16: AM_ICONV_LINKFLAGS_BODY is expanded from...
m4/iconv.m4:27: AM_ICONV_LINK is expanded from...
m4/iconv.m4:243: AM_ICONV is expanded from...
configure.ac:99: the top level
configure.ac:99: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
m4/iconv.m4:16: AM_ICONV_LINKFLAGS_BODY is expanded from...
m4/iconv.m4:27: AM_ICONV_LINK is expanded from...
m4/iconv.m4:243: AM_ICONV is expanded from...
configure.ac:99: the top level
configure.ac:99: warning: AC_LIB_RPATH is m4_require'd but not m4_defun'd
m4/iconv.m4:16: AM_ICONV_LINKFLAGS_BODY is expanded from...
m4/iconv.m4:27: AM_ICONV_LINK is expanded from...
m4/iconv.m4:243: AM_ICONV is expanded from...
configure.ac:99: the top level
configure.ac:99: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
m4/iconv.m4:16: AM_ICONV_LINKFLAGS_BODY is expanded from...
m4/iconv.m4:27: AM_ICONV_LINK is expanded from...
m4/iconv.m4:243: AM_ICONV is expanded from...
configure.ac:99: the top level
configure.ac:99: warning: AC_LIB_RPATH is m4_require'd but not m4_defun'd
m4/iconv.m4:16: AM_ICONV_LINKFLAGS_BODY is expanded from...
m4/iconv.m4:27: AM_ICONV_LINK is expanded from...
m4/iconv.m4:243: AM_ICONV is expanded from...
configure.ac:99: the top level
configure:6566: error: possibly undefined macro: AC_LIB_PREPARE_PREFIX
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:6567: error: possibly undefined macro: AC_LIB_RPATH
configure:6572: error: possibly undefined macro: AC_LIB_LINKFLAGS_BODY
configure:6580: error: possibly undefined macro: AC_LIB_APPENDTOVAR
autoreconf: /usr/bin/autoconf failed with exit status: 1

PS: I know it is for centos 7 but I thought it could be useful.

**Comment by BenjiWiebe** [comment]
You need to install gettext-devel (`sudo dnf install gettext-devel`) too. That should probably be added to the README.

**Comment by evanmiller** [comment]
Please download a tarball and start the configuration with `./configure`. The autoreconf step is only needed by developers.
