### ISSUE TITLE
Obtain character set of Access database

### ISSUE THREAD

**Issue by D4V3M0NK** [mdbtools/mdbtools#365]
Is it possible to obtain the character set of the Access database with mdb-tools?

**Comment by nirgal** [comment]
MDB bases version 4 and above are always using unicode.

Version 3 and bellow requires you to define environment variable MDB_JET3_CHARSET. See mdb-export(1). I don't think the data is anywhere in the file, unfortunately.

**Comment by D4V3M0NK** [comment]
@nirgal thanks for the response sir. From your response, having MySQL set up for utf8mb4 should handle all characters that are present in the MDB file, correct?

**Comment by evanmiller** [comment]
If it is configured with `iconv`, MDB Tools will emit UTF-8 regardless of the underlying character set.
