### ISSUE TITLE
mdb-schema and mdb-export: Support for table/field names in lowercase

### ISSUE THREAD

**Issue by jtornero** [mdbtools/mdbtools#373]
First of all, thank you very much for this tool. 

Would it be possible to export the schema/data with both table and field name in lowercase as an option?

Thanks a lot

**Comment by rhurlin** [comment]
Hi @jtornero,
Don't know if it is sufficient in your case. As a workaround you could try something with `-I postgres` like this:

```
mdb-export -I postgres database.mdb TABLENAME

mdb-schema -T TABLENAME database.mdb postgres
```
For me this works with mdbtools v1.0.0 .

**Comment by jtornero** [comment]
I finally managed to compile v 1.0.0 and it works great. Thanks a lot.
