### ISSUE TITLE
Got Error when installing on Linux RHEL 

### ISSUE THREAD

**Issue by satya5561** [mdbtools/mdbtools#382]
Trying to install on linux got following error..

`Making install in src
make[1]: Entering directory `/root/Downloads/ODBC_Client/mdbtools-master/src'
Making install in libmdb
make[2]: Entering directory `/root/Downloads/ODBC_Client/mdbtools-master/src/libmdb'
  CC       fakeglib.lo
fakeglib.c: In function 'g_locale_to_utf8':
fakeglib.c:258:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (size_t i=0; i<len; i++) {
     ^
fakeglib.c:258:5: note: use option -std=c99 or -std=gnu99 to compile your code
fakeglib.c: In function 'g_hash_table_remove':
fakeglib.c:335:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (guint i=0; i<table->array->len; i++) {
     ^
fakeglib.c: In function 'g_ptr_array_remove':
fakeglib.c:401:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (guint i=0; i<array->len; i++) {
     ^
make[2]: *** [fakeglib.lo] Error 1
make[2]: Leaving directory `/root/Downloads/ODBC_Client/mdbtools-master/src/libmdb'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/root/Downloads/ODBC_Client/mdbtools-master/src'
make: *** [install-recursive] Error 1
`

please help me to insttall it.

**Comment by itaberas** [comment]
Same problem on RHEL 7.8

**Comment by DiamondMax** [comment]
@satya5561 
There is a problem with fakeglib... 
Quick workaround: install glib2-devel package, re-run ./configure, make sure it shows "Glib enabled".
```
make
make install
```

**Comment by DiamondMax** [comment]
If you don't want to install glib2 for some reason, you can just run ./configure CC=c99 to instruct "make" to use c99 compiler

**Comment by evanmiller** [comment]
Fixed in https://github.com/mdbtools/mdbtools/commit/f14fbea09390392ca43a44bbb95fe2b1ae3a9567
