### ISSUE TITLE
1.0.0. Not Published on Debian

### ISSUE THREAD

**Issue by norsemanGrey** [mdbtools/mdbtools#388]
Seems like the Debian package version is still on 0.9.1. Any idea on when latest version will be available?

**Comment by el3um4s** [comment]
In GitHub Codespaces I get version 0.7.1

![image](https://user-images.githubusercontent.com/23579630/177532098-db33f9bb-aed4-4c17-8bd5-c1e4432e3c19.png)

**Comment by fladi** [comment]
That depends on the [release of Debian](https://tracker.debian.org/pkg/mdbtools) you are using. Debian 11 (bullseye) was released with 0.9.1 and Debian 12 (bookworm) will ship at least 1.0.0. You can of course try to request a backport of 1.0.0 to Debian 11 at the [backports mailinglist](https://lists.debian.org/debian-backports/).
