### ISSUE TITLE
libtool:   error: cannot determine absolute directory name of 'yes//usr/local/lib'

### ISSUE THREAD

**Issue by pneun** [mdbtools/mdbtools#397]
Hi, i got this error on building:

make[2]: Entering directory '/root/mdbtools/src/odbc'
  CC       odbc.lo
  CCLD     libmdbodbc.la
../../libtool: line 7580: cd: yes//usr/local/lib: No such file or directory
libtool:   error: cannot determine absolute directory name of 'yes//usr/local/lib'

this is my configuration:
configure:
configure: MDB Tools 1.0.0 - Configuration summary
configure:
configure:    SQL             : enabled
configure:    ODBC            : enabled
configure:    GLib            : disabled
configure:    iconv           : enabled
configure:    man pages       : disabled
configure:    bash-completion : enabled
configure:

**Comment by michal-josef-spacek** [comment]
I have same issue on Debian 11 in compilation with --with-unixodbc.
Output:
```Making all in odbc
make[2]: Vstupuje se do adresáře „/home/skim/22/mdbtools-1.0.0/src/odbc“
  CC       odbc.lo
  CCLD     libmdbodbc.la
../../libtool: line 7489: cd: yes//usr/local/stow/mdbtools-1.0.0/lib: No such file or directory
libtool:   error: cannot determine absolute directory name of 'yes//usr/local/stow/mdbtools-1.0.0/lib'
make[2]: *** [Makefile:469: libmdbodbc.la] Chyba 1
make[2]: Opouští se adresář „/home/skim/22/mdbtools-1.0.0/src/odbc“
make[1]: *** [Makefile:385: all-recursive] Chyba 1
make[1]: Opouští se adresář „/home/skim/22/mdbtools-1.0.0/src“
make: *** [Makefile:483: all-recursive] Chyba 1

```

**Comment by michal-josef-spacek** [comment]
Ah, bad usage of --with-unixodbc argument. Need path to unixodbc.

**Comment by michal-josef-spacek** [comment]
@pneun You need something like this (if you have pkg-config settings for unixodbc):
```
./configure --with-unixodbc=`pkg-config --variable=prefix odbc`
```
