### ISSUE TITLE
mdbexport should escape CR and LF

### ISSUE THREAD

**Issue by geithman** [mdbtools/mdbtools#40]
If a field contains CR and/or LF, then mdbexport simply puts this unescaped to the output.
There should be an option (e.g -e) to escape CR and LF to \r and \n
(Maybe this should be escaped always ?)

**Comment by evanmiller** [comment]
Please see #222 for a proposed implementation of a -e flag. Open for discussion!

**Comment by evanmiller** [comment]
Please try the new `--escape-invisible` flag in MDB Tools 0.9.1.
