### ISSUE TITLE
Fetch text of VBA module

### ISSUE THREAD

**Issue by centic9** [mdbtools/mdbtools#404]
I have an Access Database and would like to extract all information that is contained. 

Tables and DDL are well supported by mdbtools, but there is also some VBA script in one .mdb-file. 

I could not find a way to extract this with the current mdbtools.

Is it possible to add this functionality? 

Is there at some documentation about how this information is stored in the .mdb-file?

**Comment by evanmiller** [comment]
See previous discussion in https://github.com/mdbtools/mdbtools/issues/68

**Comment by centic9** [comment]
Thanks, sorry for the re-post, I'll take a look at the information there.
