### ISSUE TITLE
mdb-export does not escape backslashes

### ISSUE THREAD

**Issue by odrevet** [mdbtools/mdbtools#409]
With MariaDB/Mysql a single backslash in a string is ignored

For example, a string "12\34" in Access will be exported as-is by mdb-export 

`mdb-export -I mysql -D '%Y-%m-%d %H:%M:%S'  db.mdb mytable`

will output: 

INSERT INTO `mytable` (`myfield`) VALUES ("12\34");

But the inserted value will be 1234
SELECT myfield from mytable
=> 1234

The correct statement exported should be: 

INSERT INTO `mytable` (`myfield`) VALUES ("12\\\\34");

**Comment by mlocati** [comment]
You have to use the `--escape-invisible` option (I've just checked it and it works).

**Comment by odrevet** [comment]
Thanks for this feedback
alternatively, flag can be set when using mariadb
add sql_mode='NO_BACKSLASH_ESCAPES ad beggining of the generated file
`sed -i "1s/^/SET sql_mode='NO_BACKSLASH_ESCAPES';\n/" sql/dump.sql`
