### ISSUE TITLE
yynerrs set but not used error in parser.c

### ISSUE THREAD

**Issue by nieder** [mdbtools/mdbtools#425]
On macOS, I get this failure building mdbtools 0.9.2 through 1.0.0:
> libtool: compile:  gcc -DPACKAGE_NAME=\"mdbtools\" -DPACKAGE_TARNAME=\"mdbtools\" -DPACKAGE_VERSION=\"1.0.0\" "-DPACKAGE_STRING=\"mdbtools 1.0.0\"" -DPACKAGE_BUGREPORT=\"https://github.com/mdbtools/mdbtools/issues\" -DPACKAGE_URL=\"https://github.com/mdbtools/mdbtools\" -DPACKAGE=\"mdbtools\" -DVERSION=\"1.0.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DTLS=_Thread_local -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DYYTEXT_POINTER=1 -DHAVE_FCNTL_H=1 -DHAVE_LIMITS_H=1 -DHAVE_UNISTD_H=1 -DHAVE_XLOCALE_H=1 -DHAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME=0 -DHAVE_LIBREADLINE=1 -DHAVE_READLINE_READLINE_H=1 -DHAVE_READLINE_HISTORY=1 -DHAVE_READLINE_HISTORY_H=1 -DHAVE_STRPTIME=1 -DHAVE_FMEMOPEN=1 -DHAVE_GMTIME_R=1 -DHAVE_REALLOCF=1 -DHAVE_WCSTOMBS_L=1 -DHAVE_MBSTOWCS_L=1 -DHAVE_VASPRINTF=1 -DHAVE_ICONV=1 -DICONV_CONST= -I. -I/opt/sw/include -I../../include -I/opt/sw/include/glib-2.0 -I/opt/sw/lib/glib-2.0/include -DHAVE_GLIB=1 -g -O2 -DSQL -Wall -Werror -MT parser.lo -MD -MP -MF .deps/parser.Tpo -c parser.c  -fno-common -DPIC -o .libs/parser.o
parser.c:1035:9: error: variable 'yynerrs' set but not used [-Werror,-Wunused-but-set-variable]
    int yynerrs = 0;
        ^
```
I have GNU bison-3.8.2 installed.

**Comment by cooljeanius** [comment]
I personally think it would make most sense just to ignore this error with `-Wno-error=unused-but-set-variable`; it seems pretty harmless, and fighting with `bison` is often more trouble than it's worth.

**Comment by cooljeanius** [comment]
> -Werror is not usually a best-practice in shipped release versions. It leaves you at the mercy of diagnostics from compilers and external headers supplied by other vendors.

Yeah, removing `-Werror` entirely would also be another decent solution.

**Comment by cooljeanius** [comment]
> Maybe this is helpful somehow? [mail.gnu.org/archive/html/bison-patches/2022-08/msg00006.html](https://mail.gnu.org/archive/html/bison-patches/2022-08/msg00006.html)

Ah, apparently that was to fix akimd/bison#89; corresponding commit was akimd/bison@a166d54... I don't think it's made it into a released version of bison yet, though? It looks like the latest bison release was 3.8.2 on September 25th, 2021, and this commit was from 2022...

**Comment by evanmiller** [comment]
Fixed (ignored) in https://github.com/mdbtools/mdbtools/commit/7625bfaebfc972692b453d26f7c80d5e5fd01ebb
