### ISSUE TITLE
How to save mdb-export results as a csv file

### ISSUE THREAD

**Issue by rolandknapp** [mdbtools/mdbtools#429]
In the interest of rebuilding a few old Access databases as PostgreSQL databases, I've been testing `mdb-export` as a means of acquiring data from database tables. These attempts have been successful, but resulted in the table data getting dumped into the terminal window. How do I save the exported data to a CSV file? My code is simply `mdbtools {database name} {table name}`. Is there code I need to add to this to save the export to a CSV file? Thanks for your help. 

In case it matters, I am running mdbtools on Ubuntu 22.04.3 LTS.

**Comment by rhurlin** [comment]
Hi Roland,
Does it help to redirect your output into a file like this (greater sign)?

`mdb-export {database name} {table name} > database_table.csv`

HTH,
Rainer

**Comment by rolandknapp** [comment]
@rhurlin That worked perfectly. Thanks!
