### ISSUE TITLE
Possible Fixes for two Different Segfaults

### ISSUE THREAD

**Issue by lovelytwo** [mdbtools/mdbtools#51]
Please excuse the means at which i'm sending this patch. Very Very new to github.

While importing my data, i encounted two segfaults. I know very little about MDB/JET file format but these are the two fixes I added to allow my project to proceed. Thought I would share the fixes.
1. iconv.c mdb_unicode2ascii - EILSEQ - An invalid multibyte sequence has been encountered in the input. Added Check.
2. Zero length multiple page meno fields. Add checked to stop processing if the length is zero.

```
diff --git a/src/libmdb/data.c b/src/libmdb/data.c
index 891addb..6c7658a 100644
--- a/src/libmdb/data.c
+++ b/src/libmdb/data.c
@@ -735,6 +735,11 @@ static char *mdb_memo_to_string(MdbHandle *mdb, int start, int size)
                        if (tmpoff + len - 4 > memo_len) {
                                break;
                        }
+
+                       if(len == 0) {
+                               break;
+                       }
+
                        memcpy(tmp + tmpoff, buf + row_start + 4, len - 4);
                        tmpoff += len - 4;
                } while (( pg_row = mdb_get_int32(buf, row_start) ));
diff --git a/src/libmdb/iconv.c b/src/libmdb/iconv.c
index adc95b0..932c6e7 100644
--- a/src/libmdb/iconv.c
+++ b/src/libmdb/iconv.c
@@ -70,6 +70,8 @@ mdb_unicode2ascii(MdbHandle *mdb, char *src, size_t slen, char *dest, size_t dle
        //printf("1 len_in %d len_out %d\n",len_in, len_out);
        while (1) {
                iconv(mdb->iconv_in, &in_ptr, &len_in, &out_ptr, &len_out);
+
+               if ((!len_in) || (errno == EILSEQ)) break;
                if ((!len_in) || (errno == E2BIG)) break;
                /* Don't bail if impossible conversion is encountered */
                in_ptr += (IS_JET3(mdb)) ? 1 : 2;
```

**Comment by nirgal** [comment]
Regarding the data.c part, Adam D. Barratt pointed out that len should be checked >= 4 rather than not 0.

https://bugs.debian.org/780471#10

**Comment by evanmiller** [comment]
@nirgal the <= 4 length check is present in #162

The iconv length check was covered in https://github.com/mdbtools/mdbtools/commit/9d56b0c3d80cdabc21bc4af0f9bba849b24035f0

Closing issue
