### ISSUE TITLE
pyodbc.Error: ('HY000', 'The driver did not supply an error!')

### ISSUE THREAD

**Issue by damufo** [mdbtools/mdbtools#56]
O: debian wheezy

Code:
###### 
# -_\- coding: utf-8 -_-

import os
import pyodbc

db_path = "bd1.mdb"
print db_path

odbc_connection_str = 'DRIVER={MDBTools};DBQ=%s;User Id=admin;Password=;' % (db_path)

connection = pyodbc.connect(odbc_connection_str)
cursor = connection.cursor()

queries = []
queries.append( "SELECT \* FROM TABLE1")
queries.append( "SELECT \* FROM TABLE2")

for query in queries: 
    print query
    cursor.execute(query)
    rows = cursor.fetchall()
    for row in rows:
        print row
###### 

output:
SELECT \* FROM TABLE1
('00001\x00', '12345\x00', None)
('00002\x00', '12346\x00', None)
SELECT \* FROM TABLE2
Traceback (most recent call last):
  File "/home/eu/pro/cpun/src/script.py", line 19, in <module>
    cursor.execute(query)
pyodbc.Error: ('HY000', 'The driver did not supply an error!')
###### 

I think that the problem are fields type numeric.
The TABLE2 have a numeric field.
Exist any solution?

Very thnaks!!

**Comment by tthurman** [comment]
This was fixed by dca7552d on 2015-05-22. The Python ODBC library attempts to check SQL_DESC_UNSIGNED which fails.

**Comment by tthurman** [comment]
@brianb , do you think we can have a new release now that mdbtools ODBC can be used from Python?

**Comment by evanmiller** [comment]
Closing issue since this is fixed in master. We will have a new release in the coming months.
