### ISSUE TITLE
mdb-export fails with a g_hash_table_lookup error

### ISSUE THREAD

**Issue by mesimms** [mdbtools/mdbtools#57]
I'm on Ubuntu 12.04: I installed mdbtools through the package manager and have the following problem: 
I type: mdb-export myfile.mdb mytable
I get: GLib-CRITICAL **: g_hash_table_lookup: assertion `hash_table != NULL' failed"
I then compiled from this repository (and used Fix #37 to get the configure to work) and I still get the same result.
My ldd --version returns:
ldd (Ubuntu EGLIBC 2.15-0ubuntu10.5) 2.15
Any ideas?

**Comment by w3b-beweb** [comment]
thanks @mobi278! I have an ubuntu 12.04, upgraded from a 8.04 where mdbtools was installed via apt-get, then recompiled from source to obtain the accdb compatible version. After upgrade to 12.04 I started to get this error. Removing  libmdb2, libmdbsql2 and mdbtools-dev fixes it.

**Comment by nirgal** [comment]
I think this error occurs when using an old version of libmdb, that doesn't call mdb_init automatically on load, with an new version of the utils binaries.
