### ISSUE TITLE
Link on installation quide in faq.html is incorrect

### ISSUE THREAD

**Issue by rutsky** [mdbtools/mdbtools#74]
Link here is broken: https://github.com/brianb/mdbtools/blob/dd0f4c3819a73f7a757f6d9a20cc4d747f813bd0/doc/faq.html#L81
(https://raw.github.com/brianb/mdbtools/master/INSTALL)

As I see, installation guide on SourceForge project page is http://mdbtools.sourceforge.net/install/ and these files are completely missed in github repository.

**Comment by evanmiller** [comment]
This documentation is known to be outdated and will be removed soon. Thanks.
