### ISSUE TITLE
Github repository status

### ISSUE THREAD

**Issue by rutsky** [mdbtools/mdbtools#75]
I see that MDB Tools on SourceForge is still active: it has relatively recent bug reports and messages in mailing list.
Official page http://mdbtools.sourceforge.net says that code can be obtained from CSV repository on SourceForge.

What is the status of this Github repository? Shouldn't bug reports to be moved in one place and official page updated?

**Comment by evanmiller** [comment]
We are in the process of consolidating everything into GitHub – closing issue.
