### ISSUE TITLE
Access 2013 support

### ISSUE THREAD

**Issue by eric-cs** [mdbtools/mdbtools#77]
It would be great if mdbtools could support Access 2013 files as well. As it already supports Access 2010 files, I hope it's not a big deal to implement this enhancement.

When trying to connect to an Access 2013 file, mdbtools exits with the following error: "Unknown Jet version."

Access 2010 files with the same file suffix (.accdb) work just fine.

**Comment by barnakb** [comment]
Facing same issue trying to extract .accdb using mdbtools.

**Comment by barnakb** [comment]
A reinstall of the mdbtools fixed the problem.

**Comment by eric-cs** [comment]
Interesting, how did you re-install mdbtools? From source? Or from any package installer?

**Comment by masseo1** [comment]
I assisted barnakb in this, we installed from source, con centos 6.6.
My intention was to build an rpm package with the  included "mdbtools.spec" file, using  "rpmbuild -ba  mdbtools.spec", as I wanted this to be portable for other systems in the environment.  The rpm building didn’t happen, as I was chasing around a docbook dependency that held me up.


I had to get all of the dependencies met, as well as make sure all of the needed dev tools were on the system, then used autoconf to make the configure file, then did the standard "configure,make,make install". We don;t need the UI, so I ran configure with "./configure --disable-gmdb2"

I might play with building the rpm again, sometime next week.

Cheers.

**Comment by masseo1** [comment]
I was able to build rpms for Centos 6.6 x86_64
I had to modify the mdbtools.spec file a bit to get it to work.
basically, I added files that were considered "unpackaged" to the following:
%files
%{_bindir}/mdb-prop

%files devel
%{_includedir}/mdbver.h

%files odbc
%{_libdir}/libmdbodbcW.a
%{_libdir}/libmdbodbcW.la
%{_libdir}/libmdbodbcW.so
%{_libdir}/pkgconfig/libmdb.pc
%{_libdir}/pkgconfig/libmdbsql.pc

results this time around:
Wrote: /root/rpmbuild/SRPMS/mdbtools-0.7.1-1.src.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/mdbtools-0.7.1-1.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/mdbtools-devel-0.7.1-1.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/mdbtools-odbc-0.7.1-1.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/mdbtools-debuginfo-0.7.1-1.x86_64.rpm


Cheers

**Comment by eric-cs** [comment]
Many thanks for the detailed explanation. I'll try to get it work the same way on Debian.

**Comment by Skywalker-11** [comment]
Did you managed to fix it under Debian? I'm having the same problem with Debian jessie. If I use a database which not contains features from the new format (like calculated fields) everything works fine. As soon as I create a single field in a table which is from type calculated field I only get "Unknown Jet version". Reinstall didn't work for me

**Comment by eric-cs** [comment]
Unfortunately, I didn't find the time to fix it under Debian until now.

**Comment by amitailanciano** [comment]
Is this still unresolved?

**Comment by eric-cs** [comment]
Yes, unfortunately it's still unresolved.

**Comment by smaudet** [comment]
FYI the JET version I get is 2ACE12 (this is for a recent 2013 document I believe, although the original creator of the document claimed it was created in 2002).

**Comment by mdjnewman** [comment]
I'm having trouble with an Access file, though I need to confirm exactly which version of Access it was produced with.

I've opened a small PR (#125) to make debugging this a little easier. Using this PR, I know the value of `mdb->f->jet_version` is `0x03`.

**Comment by evanmiller** [comment]
@mdjnewman Did you figure out which version of Access sets `jet_version` to `0x03`? I am seeing a file in the wild with the same value.

**Comment by mdjnewman** [comment]
@evanmiller I think it was 2016, but I'm not sure now. May also only be for a database that uses the large number functionality. Sorry my answer isn't more useful!

I'm using http://jackcess.sourceforge.net/ at the moment which is working well, [JetFormat.java](https://github.com/jahlborn/jackcess/blob/master/src/main/java/com/healthmarketscience/jackcess/impl/JetFormat.java#L52) might have the answers you're looking for.

**Comment by evanmiller** [comment]
Fix included in #162
