### ISSUE TITLE
JOIN functinality

### ISSUE THREAD

**Issue by sashman** [mdbtools/mdbtools#80]
Hello, I am trying to track down any activity to do with the implementation of JOINs, but so far only spotted a mention on the road map.

Could you please update me on any progress which has been made, if any, on this feature? Any foreseeable plans to work on this?

Cheers!

**Comment by nirgal** [comment]
Hello

Unfortunately, nobody took the time to implement that feature yet.

I don't plan to work on this any time soon, and brian has been idle for a while now.

So don't expect that feature any time soon.
